### PR TITLE
Updated .NET FRamework to 4.8 and enabled HDPI support

### PR DESCRIPTION
**Pull request by IgorTheLight**
+ Added all changes from 1.5.2 version from here: https://www.moddb.com/mods/ultimate-apocalypse-mod/downloads/dow-mod-manager-v152
+ Updated target framework from .NET Framework 4.5 to 4.8 (it's supported even on Windows 7)
+ Enabled Windows Forms HDPI Awareness in app.config and app.manifest. First step to correct rendering on Windows Scaling > 100%
+ Enabled Process DPI Aware. Second step to correct rendering on Windows Scaling > 100%
+ Some small tweaks in code. Now application uses 100 Kb less memory. Yay! :-)

### CODE REVIEW

**Review by Fragjacker — CHANGES_REQUESTED** [review]
# Change Request

## Mod Manager main UI
The normal Mod window has some issues with the labels for the windows as they appear in the wrong place when the window is maximized.

image

This is how it should look like

image

## Mod Merger UI
The Mod Merger UI is busted as well as important UI elements are suddenly gone. Below image shows the Mod Merger from your pull and the right is the one from my old v1.52 as how it should look like.

image

These issues must be fixed first, before a merge is possible.

**Comment by IgorTheLight** [comment]
Thanks for reply.
HDPI is hard to tweak: when it looks good with 100% - it looks weird on
100%+. And vise versa.
I thing it will be a smarter idea to do this step by step (instead what I
did). So I will do that is a few steps:
* Fork your repository
* Implement 1.5.2 from moddb
* Make a pull request to your master branch
* If you accept it - I will try to do some small tweaks.
* Make a pull request to your master branch with those small tweaks
* If you'll like it - I will try to make it DPI independent.
I have a small question: why your last version is 1.5.1 when I can find a
1.5.2 here https://www.moddb.com/mods/ultimate-apocalypse-mod/downloads
Was it not created by you? Or you just forgot to update it on GitHub?
Thanks.

**Comment by IgorTheLight** [comment]
There is zero difference between your last build from 1.5.1 and 1.5.2 from
moddb.
So you just forgot to update README.md file!
I see now!

**Comment by Fragjacker** [comment]
@IgorTheLight Yes I have forgot to do several updates on my repo my, bad :(
 The latest version is also not yet merged to the master branch as well. It's located on the `v1.5` branch. I really should merge it into master and do the necessary edits to the README.md file!

**Comment by Fragjacker** [comment]
@IgorTheLight Updated the master branch with the latest stuff just now!

**Comment by IgorTheLight** [comment]
You also added a Release so it's more convenient to download an executable
if needed.
Nice!

Please review my pull request - It's not that broken as my previous :-)

**Pull request closed without merging**
