### PR TITLE
I fixed a rare bug and enhanced one method

### PR DESCRIPTION
**Pull request by IgorTheLight**
- Fixed a crash when there is no line 15 in spdx9_config.txt file in Drivers folder (thanks,  SergeantDiggs)
- WriteSettings() method in SettingManagerForm is more efficient now -allowhwcursor it uses StreamWriter instead of StringBuilder( + File.WriteAllLines())

### CODE REVIEW

**Comment by IgorTheLight** [comment]
I hope you are ok and just busy...
If you need some help - you may write here (not many people came here so it's half-private) or send me an e-mail igorthelight@gmail.com
Take care :-)

**Comment by Fragjacker** [comment]
Oof yeah I am indeed kinda busy for sure. I should be able to review this tomorrow as Github throws the usual fit about merge conflicts that I have to solve manually.

**Comment by IgorTheLight** [comment]
Sounds kinda mysterious ;-)
I'm glad that you are fine

**Review by Fragjacker — CHANGES_REQUESTED** [review]
I have found several code pieces that would be reverted when merging your changes which tells me that this is not using the latest code from my repository. Please update your fork and subsequently your pull request before I can merge.

The best way is to add the original repository to your fork as an upstream so you can easily update anytime:
```
# Add the original repo as an upstream

git remote add --track master upstream git@github.com:Fragjacker/DoW-Mod-Manager.git

# Now grab the latest changes

git fetch upstream

# Make sure that you're on your master branch:

git checkout master

# Rewrite your master branch so that any commits of yours that
# aren't already in upstream/master are replayed on top of that
# other branch:

git rebase upstream/master

# If you've rebased your branch onto upstream/master you may need to force the push in 
# order to push it to your own forked repository on GitHub. You'd do that with:

git push -f origin master

```

**Comment by IgorTheLight** [comment]
Ah, ok!
You remember that I like to do things in an easy (but a little bit wrong way ;-) )
But I will do the right thing this time!

**Comment by IgorTheLight** [comment]
I can't fetch from upstream because of that:
>>>
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
>>>
GitKraken says that I have problems with SSH keys when I would try to do the same action using it: Configured SSH key is invalid.
So, the problem is in just one file - DoW Mod Manager/LatestStable/DoW Mod Manager.exe
Of course those are two different files - yours is from 2.2.0 while mine is from 2.2.1
If I would have some more unusual code - wouldn't we have more conflicting files?
I would just delete DoW Mod Manager.exe just for my pull request ;-)

**Comment by IgorTheLight** [comment]
Looks like GitHub likes DoW Mod Manager.exe from version 2.2.0 ;-)
I know - that's not the correct way to do that... But it's already working! You should just build "DoW Mod Manager v2.2.1.exe" and copy it by executing "CopyExecutableHere.cmd".
P.S. I don't remember why exactly I added SSH keys so I don't want to mess with them. But I could if you say that there are still problems ;-)

**Comment by Fragjacker** [comment]
Now this is proper weird now. The binary was not the problem here. The issue is with the `Minibrowser.Designer.cs` and `Minibrowser.cs` file. When I look at Github Files changed tab this file doesn't show up as changed, but when I fetch the pull locally on my machine and then Diff it to my master branch it shows this file as changed. I have changed the minibrowser icon in my recent push to fit the rest of the app, but when I build your version the icon is again missing. This indeed confirms that said file is overwritten by this pull, yet it doesn't show up as in the changed files tab? Below I attached images of my local diff of the said overridden files.
image
image
Thankfully these changes would be simple to merge back in but I am really concerned why this file change is not highlighted by Github in the first place.

**Comment by Fragjacker** [comment]
On the matter of the SSH key, you'll have to generate yourself a SSH key first. This tutorial describes how to do this: https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

Alternatively you can try substituting:

`git remote add --track master upstream git@github.com:Fragjacker/DoW-Mod-Manager.git` 

with

`git remote add --track master upstream https://github.com/Fragjacker/DoW-Mod-Manager.git`

And see if that works, since that one doesn't require you to have an SSH Key created.

**Comment by IgorTheLight** [comment]
That's strange that Git doesn't see the diffs in those two files.
About SSH - I installed My SSH key in GitKRaken some times ago - maybe it's interfering with fetching.
I could try to fix that or I could just take your two files and the problem will be solved instantly (and that doesn't make anything worse - I will just remember that I must be more careful with SSH keys)

**Comment by Fragjacker** [comment]
Alright I have merged this pull request but I also did some small changes to it. I would advise you to pull the latest changes from my master branch to be safe 😁 .

**Comment by IgorTheLight** [comment]
Ah, ok!
I will ;-)

**Pull request merged**
