### PR TITLE
1.7.0 here! Ready and willing!

### PR DESCRIPTION
**Pull request by IgorTheLight**
- Added new form - Mod Downloader. It could download most popular mods using your default web browser
- Some code improvements
(I'm waiting for README.MD merge problem :-) )

### CODE REVIEW

**Comment by Fragjacker** [comment]
# Merge conflict
Oh boi this time it's a bit more to merge 😬 . Also the obligatory README.MD conflict ;-).
## Conflicting files
```
DoW Mod Manager/DoW Mod Manager.csproj
DoW Mod Manager/ModManagerForm.cs
DoW Mod Manager/ModMergerForm.cs
README.md
changelog.txt
```
Make sure you merged the latest master branch into yours and resolved the conflicts proper. For this I am usually using http://meldmerge.org/ as the mergetool because it's so nicely verbose and you can easily merge text based files. 👌

**Review by Fragjacker — CHANGES_REQUESTED** [review]
# Change request
Alright I have looked at the mod downloader and it looks pretty neat! However I'd remove the `Open ModDB.com` button since it serves no purpose really in the context of fetching particular mods. Also the list of downloadable mods should be sorted alphabetically so it's easier to find particular mods.
## Optional suggestions
It would be also nice if all dependency mods, required to run the selected mod, could also be easily downloaded directly. Maybe you could extend the main window with such functionality since it already lists dependency mods. Currently the user has to manually go over all dependancies and look them up from the list of mods.  Also you may even want consider adding a search bar, in case the list of downloadable mods grows even larger.

**Comment by IgorTheLight** [comment]
About conflict merging tool - Meld looks nice but I have probably even
better thing - GitKraken. It's a full Git managing solution (create,
delete, merge - you name it). https://youtu.be/ub9GfRziCtU
I could even say that GitKraken for Git is the same as DoW Mod Manager for
Dawn of War - it makes it "casually easy" ;-)
About changes - yes I agree that opening ModDB is not that useful but it
opens MdDB + DawnOfWar Mods + sorting it by user rating. So it's kinda
useful... I'm not sure.
About alphabetical - I agree. I will change it now or in 1.8.1 (so very
soon in any way).
About it integration in main Frame or any improvements - yes I WILL
definitely improve it. For 1.8.0 his existence is already a good thing :-)
Maybe sorting it alphabetical is a good thing for 1.8.0

**Comment by IgorTheLight** [comment]
Also the logic behind "Open ModDB.com" is like this:
"Ah shit! My favorite mod is not here!" - well that button opens ModDB on
DoW mods page. It's "Do it yourself" button.
Maybe I'll delete it in future. Or rename it to something more suitable.
Let it sit there for one patch :-)

**Comment by Fragjacker** [comment]
Ah yes Gitkraken. I have been using it for a while but it is unfortunately proprietary software which has some functionality blocked behind a paywall. Another very similar and free tool is https://www.sourcetreeapp.com/ . I am however keep using command line tools such as Git bash and posh git https://github.com/dahlbyk/posh-git since you can do stuff with them that you can't do with GUI clients 😁 .

**Comment by IgorTheLight** [comment]
I like your idea - take good things from different sources so you could
have the best overall experience :-)

**Comment by IgorTheLight** [comment]
I'm sorry for creating MasterX branch but I couldn't merge to a normal master branch - button just doesn't work. I tried in Firefox 77.0.1 and Edge 44.19041.1.0

**Comment by Fragjacker** [comment]
@IgorTheLight Here the command line tools prove to be king once again 😁 , check out this article https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/merging-an-upstream-repository-into-your-fork how to merge from another repository, then you can use some mergetool to resolve the conflicts proper locally then push to your repo.

**Comment by IgorTheLight** [comment]
Thanks.
It's strange that problems are appearing out of thin air. I resolved all
problems (all of them were stupidly easy to solve - Git could do that by
itself to be honest).
While I'm reading the article you could do a very simple thing - clone my
master branch and copy it on top of your master branch then push as a
commit. That's very "cheap" but it could be done in less than a minute. Our
differences are minimal (capital letter instead of non-capital or a few
spaces more + my new lines of code).
Or I will try to resolve it in a proper way very soon.

**Comment by IgorTheLight** [comment]
I made two videos to show WHAT kind of problems Git couldn't resolve by itself and why I'm stuck:
https://www.youtube.com/watch?v=IYCqHJCJNpQ
https://www.youtube.com/watch?v=6YjcPwlW--I

**Comment by Fragjacker** [comment]
Hehe yeah manual online merge conflict resolving is garbage. Either use some GUI client or command line tools to resolve them locally on your comp and then push directly to your repo. I am usually using Meld for this since it allows for swapping changes easily. Sourcetree should work too for this or any other client with a proper mergetool incorporated.

**Comment by IgorTheLight** [comment]
I have a dilemma - keep trying to resolve this or create a new pull request
in a few days.
1.8.0 is coming ;-) (SettingsManager).
And of course I have to think about a fun name for that update - this is
the most important part! :-)
1.7.0 "Ready and willing" is not that ready, sadly! Git doesn't like me
anymore.

**Comment by Fragjacker** [comment]
Alright I have used my divine command line tools powers to resolve the conflicts for you and merged it into master now 😁 .

**Comment by IgorTheLight** [comment]
Thanks!
I basically choose the second option - don't bother with 1.7.0 when 1.8.0
will have the same issues in a few days. Well - it most likely will :-)
But if you get the 1.7.0 - it's fine too! :-) You could test some mod
downloading capabilities of my wonderful (but very simple and without any
search and automated features) module!
SettingsManager is on the way! It already could read, show in UI, change
and write back the changes. It just lacks some polish. 1.8.0 will have NO
improvements for any other parts of the program - there will come in 1.8.1
and 1.8.2
But none the less - thanks for taking care of 1.7.0 :-)

**Comment by IgorTheLight** [comment]
Hi!
1.8.0 is ready! I'm not sure what would be faster - create a pull request
with a ton of issues or you just grab my sources for Releases and commit
them as your own. I'm really not trying to run from the problems - just
trying to make our lives easier ;-) I will do as you ask in that regard.
Let's call that update... ummm... 1.8.0 - "The Machine Spirits are willing"
The next update would be 1.8.1 - optimizations and refactoring. Our EXE
file will be much lighter in 1.8.1 - I have a good idea how to do that ;-)
About other refactoring. I will basically see through ALL the code (again)
and will try to improve it. You have the last chance to say "Please no! Not
the improvements!" before I started ;-)

**Comment by Fragjacker** [comment]
@IgorTheLight A pull request is definetely the way to go, even if I just merge it with my command line powers, just so that it shows up pull request history for anyone to know the origins of the changes 😁 .

> Let's call that update... ummm... 1.8.0 - "The Machine Spirits are willing"

I am fine with that.

> The next update would be 1.8.1 - optimizations and refactoring. Our EXE
file will be much lighter in 1.8.1 - I have a good idea how to do that ;-)
About other refactoring. I will basically see through ALL the code (again)
and will try to improve it. You have the last chance to say "Please no! Not
the improvements!" before I started ;-)

The code of my Mod Manager has been mostly written _years_ ago so I am not surprised if there are better ways to do this. Cleanups and Refactorings are always a welcomed addition! Also feel free to remove unused outcommented old code. 😀

**Comment by IgorTheLight** [comment]
Ah thanks!
I think DoW Mod Manager is in a good state! It was in a good state even
before I joined :-)
I saw an interesting thing -
https://github.com/THEONLYDarkShadow/Dawn-of-War-Mod-Manager
So this one is a C++ (wxWidgets Framework) port of your earlier version?
There is also this thing (an ancient relic - 2006 year)
https://www.moddb.com/games/dawn-of-war/downloads/mod-manager-2-2
I never heard of this before! It seems like only your project has survived!
:-)
I'm not sure WHY I'm looking for all those relics - maybe that's some
Librarian thing going on ;-)
Don't worry - I'm not going anywhere! I'm just (suddenly) interested in Mod
Manager story. I used only this one. We don't even have a proper competitor!
That's most likely because DoW1 is not THAT popular and community is having
fun with your DoW Mod Manager and not really have any reason to create
another one.
Forks are created because someone is not satisfied with the program. Guess
there is no such problem here!
And after a few additions there will be even less reason to start a Heresy
;-)

**Comment by Fragjacker** [comment]
> https://github.com/THEONLYDarkShadow/Dawn-of-War-Mod-Manager

This one has an interesting feature. Reading the warnings.log file to prompt the user any issues if a mod crashes. This would be handy because currently the Mod Manager _only_ scans for all *.module files and then checks if their folders _exist_ and not if they are actually complete. Hence mods can crash even if they appear as installed because they are corrupted or didn't even fully installed all contents in the first place. Critical crashes in warnings.log files usually look like this `MOD -- Fatal Data Error`. It would be cool to have some handling by the Mod Manager for this case 😀 .

**Comment by IgorTheLight** [comment]
Sounds interesting! This may be a new feature for 1.9.0
Also I'm looking at "Time Resolution" an interesting Windows thing that all
games have to change to boost performance. I have to check if DoW changes
it or not.
Crysis 3 didn't change it before some patch :-)
https://vvvv.org/contribution/windows-system-timer-tool
https://github.com/tebjan/TimerTool

**Pull request merged**
