### PR TITLE
Version 2.3.0.0 is out!

### PR DESCRIPTION
**Pull request by IgorTheLight**
- Added a Font Manager. Now you can add new fonts, and change fonts sizes for different UI elements!
- Some small code improvements

! I also wanted to add ability to find DoW folder if we are not in it - but Font Manager is more useful so I would just push that feature further ;-)

### CODE REVIEW

**Comment by Fragjacker** [comment]
> ! I also wanted to add ability to find DoW folder if we are not in it - but Font Manager is more useful so I would just push that feature further ;-)

Well it looks like I got you covered then. The font manager will make a nice addition to the folder finder for sure. I gotta review this since Github is having a seizure again marking stuff for conflicts.

**Review by Fragjacker — COMMENTED** [review]
Alright I have tested your pull request and ironed out some merge weird merge conflicts. One thing that I would request:

- When attempting to open the font manager it tells you to install A larger fonts mod first. For convenience sake I would add an option like "Do you wish to download it now?" Yes/No and open the mini browser for them.

**Comment by IgorTheLight** [comment]
I thought about that but I was too lazy to implement that ;-)
It will be in 2.3.1.0 (with a DoW finder)
About Folder Finder - do you mean your new feature to open DoW directory or you are working on a way to find DoW game directory wherever it could be? (using a Registry, most likely)
Your new button is very useful if someone would start DoW Mod Manager from A Desktop shortcut - we should add it earlier ;-)

**Comment by Fragjacker** [comment]
> or you are working on a way to find DoW game directory wherever it could be? (using a Registry, most likely)

Funnily the early versions of the DoW Mod Manager had the code to read registry codes though this was dropped in favor of local based installations. It allowed multiple Mod Manager instances on the same computer and included CD DoW version that may or may not have written registry keys.

**Comment by IgorTheLight** [comment]
Makes sense :-)
Of course, DoW Mod Manager could be smart and search locally, then in Registry for multiple versions...
The question is: do we need that? And the answer would be.. nah, not really ;-)

I would post all Registry keys that are corresponding to a Steam installation (in case someone would need them):
Computer\HKEY_CURRENT_USER\SOFTWARE\Valve\Steam\Apps\4570 - DoW
Computer\HKEY_CURRENT_USER\SOFTWARE\Valve\Steam\Apps\9310 - WA
Computer\HKEY_CURRENT_USER\SOFTWARE\Valve\Steam\Apps\4580 - DC
Computer\HKEY_CURRENT_USER\SOFTWARE\Valve\Steam\Apps\9450 - SS

Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Steam App 4570
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Steam App 9310
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Steam App 4580
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Steam App 9450

Computer\HKEY_USERS\S-1-5-21-2778106714-2705624015-1411336348-1001\SOFTWARE\Valve\Steam\Apps\4570
Computer\HKEY_USERS\S-1-5-21-2778106714-2705624015-1411336348-1001\SOFTWARE\Valve\Steam\Apps\9310
Computer\HKEY_USERS\S-1-5-21-2778106714-2705624015-1411336348-1001\SOFTWARE\Valve\Steam\Apps\4580
Computer\HKEY_USERS\S-1-5-21-2778106714-2705624015-1411336348-1001\SOFTWARE\Valve\Steam\Apps\9450

**Pull request merged**
