### PR TITLE
Version 2.1.0 is here! ""

### PR DESCRIPTION
**Pull request by IgorTheLight**
- Added a new mod to download for Dark Crusade - Cinematic Battles (Version 1.5)
- Ultimate Apocalypse mod was updated from 1.88.731 to 1.88.742 (with a new Titan!, bugfixes and balance changes!)
- Added a few popular 16:10 resolutions
- ModDownloaderForm could be resized and maximized now
- SettingsManagerForm could be resized and maximized now
- Modlist for ModDownloaderForm is stored in an external file now and could be modified by the user!
- Modlist for ModDownloaderForm can be updated from GitHub automatically!
- Old version of DoW Mod Manager could be automatically deleted while autoupdating even if it was renamed by the user
- Updated .NET Framework from 4.7.2 to 4.8 (the last version)
- Changelog now has only information about the last version with a link to a full changelog on GitHub
- Added ability to enable Singlethreaded JIT compilation - a default setting for .NET Framework applications
- Added a few new Actions and streamlined the code
- Deleted author and version number in ModMergerForm (with a permission from FragJacker)
- Increased SettingsManager Form size a little bit for better readability
- All dialogBoxes will have title bars (even if title is empty)

* Large font is NOT in this version - there are too many changes already!
* You could change from where it downloads the modlist (but then you will have to update it frequently)

### CODE REVIEW

**Comment by Fragjacker** [comment]
Very nice push there! I will test it ASAP!

**Review by Fragjacker — APPROVED** [review]
All works and looks nice! For the mod list we will eventually have to move it to the main repository so that all files are distributed from one central location but that's for the future.

**Comment by Fragjacker** [comment]
Alright this bad boi got merged! Tomorrow I'll go into vacation for two weeks so don't worry if you hear nothing from me 😛 .

**Comment by IgorTheLight** [comment]
Ah! Ok!
Happy holidays! ;-)

**Pull request merged**
