### PR TITLE
2.0.0 is out! "Someone call for an earthshaker?"

### PR DESCRIPTION
**Pull request by IgorTheLight**
## Version 2.0.0:

- Added a new form - System Performance Manager. This tool is able to change system-wise settings for better performance
- Added a new form - About (authors + homepage + updates + changelog + license). Yes - DoW Mod Manager could update to a newer version just with ONE click of a mouse!
- Added a new form - Message - now all error messages will have the same theme as all main forms (and it's helper class - ThemedMessageBox)
- Replaced all error messages from MessageBox to ThemedMessageBox
- Added ability to search for mods in Mod Downloader (to achieve this result, the whole ModDownloaderForm was rewritten).
- Added ability to find a missing mod
- Added ability to create, rename and delete Player Profiles (in Settings Manager)
- Added ability to change and save "Invert Declination", "Invert Pan" and "Scroll Rate" in Settings Manager
- Now all profiles are shown as PLayer names instead of numbers ("YourName" instead of "Profile1")
- Added version descriptions to all mods in Mod Downloader
- Added version detection for mods in Mod Manager
- Added ability to show Critical errors from warnings.log
- Added a new mod to download - Imperial Fists (Version 3.0)
- Added a new mod to download - Dawn Of Skirmish AI Mod (Version 3.20)
- Updated CornCobMan's Fun Mod for Soulstorm (from 1.87 to 1.88.4)
- Updated Veteran Mod for Dark Crusade with additional file links that are required
- Fixed a bug where ScrollRate and Gamma could be saved incorrectly
- Changed "goto" statement in ModManagerForm (in Thread handling) to more modern "while" loop
- Aggressive inlining were requested for all methods with only one call (performance impact will be tested in future but most likely it will be positive)
- All Soulstorm mods in modlist (ModDownloaderForm) have a new attribute now - "ModuleFileName".
- Renamed all non-lowercase image resources (such as Checkmark.png and Checkmark_disabled.png)'
- Renamed "DoW Mod Manager Resources" to just "Resources"
- Resized all image resources to 50 px hight. Resource folder is now 56 Kb instead of 268 Kb (21% of original size). It even looks better now (less artifacts when it's stretched).
- Because of resource optimizations DoW Mod Manager executable is 643 Kb instead of 1085 Kb (59% of original size)
- Changed a few colors - application theme is more consistent now
- "cancelButton" was renamed to "closeButton"
- Added IgorTheLight to the authors (thanks, FragJacker!)
- Added annotations for all methods in ModManagerForm
- Small code tweaks and optimizations here and there

Prepare your merging tools - they will get hot! ;-)

### CODE REVIEW

**Comment by Fragjacker** [comment]
Oh my! That list of features be huge 😁 . I will test this ASAP! Automatic update etc is something I wanted for a _long time_! How are you fetching the updates? Are you downloading the release version executable zip files with the .exe in it?

> Changed "goto" statement in ModManagerForm (in Thread handling) to more modern "while" loop

So you read Dijkstra's `Goto considered harmful`? 😀

**Review by Fragjacker — CHANGES_REQUESTED** [review]
Ok when clicking the `SETTINGS` button I get an exception:

```
System.FormatException: Die Eingabezeichenfolge hat das falsche Format.
   bei System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   bei System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   bei System.Convert.ToInt32(String value)
   bei DoW_Mod_Manager.SettingsManagerForm.ReadSettingsFromPlayercfgLUA()
   bei DoW_Mod_Manager.SettingsManagerForm.CurrentPlayerComboBox_SelectedIndexChanged(Object sender, EventArgs e)
   bei System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   bei System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   bei DoW_Mod_Manager.SettingsManagerForm.InitializeGUIWithSettings()
   bei DoW_Mod_Manager.SettingsManagerForm..ctor(ModManagerForm form)
   bei DoW_Mod_Manager.ModManagerForm.SettingsButton_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.Control.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
   bei System.Windows.Forms.Button.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by IgorTheLight** [comment]
"Look at the size of this thing"! - Imperial Guardsman :-)
How I did the autoupdates? As usual: the simpler - the better! So it works
like this:
* There is a folder called "LatestStable" with a *.cmd script that copies
an executable from a \bin\Release folder and renames it to just "DoW Mod
Manager.exe". This part must be done by a developer after he builds a new
update
* In that folder there is also a file named "version" - it contains the
version of a new executable. Developers have to write manually a new
version there. I will probably make it automatic in future.
* In "AboutForm" there is a button "Update" - it checks what version DoW
Mod Manager is (AssemblyVersion) and compares it to what is in "version"
file (on GitHub project's page) It it's smaller - it downloads an
executable from GitHub project's page to a Dawn of War directory and
renames it to $"DoW Mod Manager v{newVersion}.exe" (your brain have to
concatenate this string ;-) )
* After that your current version of DoW Mod Manager closes and opens a new
one.
So ALL that user has to do is to follow a goddamn train!
Hmmm...
I mean - just press an "Update" button! :-)

About "goto" - well, I can't really tell where I learned that this is not a
good practise. But I will still use it where I can't find a better
solution. So there is one place in SettingsManager where it's still in use
(to fall through the non-empty "case" statements) :-)
"while" loop is an abstraction for a conditional jump. "goto" is just a
non-conditional jump. So using a "goto" is like trying to write an x86
Assembly in your high level language :-)
Java even doesn't have a "goto" statement at all! But what if I feel really
brave today? ;-) I think language has to let you shoot yourself in the foot
(just write something like "enable_unsafe_instructions" or something). So
that's one of the reasons why I like C# more :-)
I will probably like C++ even more but syntax is kinda archaic. But on the
other hand it has some nice things.

**Comment by IgorTheLight** [comment]
Oh shit!
Something wrong with a Regional Format! I will look into it (I don't have
this problem btw).
I will probably switch language on my second PC to German to test it! Or
maybe install it in a VM.

**Comment by IgorTheLight** [comment]
You may test other things for now (autoupdater, new ThemedMessageBox and
other things that are not in Settings)

**Comment by Fragjacker** [comment]
>You may test other things for now (autoupdater, new ThemedMessageBox and
other things that are not in Settings)

I have tested the other stuff and it looked solid. However the UI looks a biti packed full with buttons now, guess I gonna have to do a slight redesign so it looks a bit less cluttered. 

I would also advise doing the Mod Manager update check each time the app is started instead of relying on the user to do this manually. That will be more convenient and will cause less questions from people how to update the Mod Manager. Never rely on the knowledge of the user, he will disappoint you 😀. On our discord we had plenty of people that been asking on how to activate the LAA patch even though I put a nice button and red text directly in front of their face 😬 .

**Comment by IgorTheLight** [comment]
Agree about UI being cluttered. It's just too many buttons now! Redesign is
surely needed! :-)
About users - true. Applications have to work "by itself". But on the other
hand - Power Users hate when an application does that! So I have to enable
"Machine Spirit" by default but make it deactivatable for Advanced Users :-)
I am installing it on my parents laptop so I could test it there. Maybe
your Exception will show there? If no - I would have to install an VM to
test it there.

**Comment by IgorTheLight** [comment]
I tested it on my parents laptop. Your Exception isn't there but I fixed 2
bugs already (when you have no mods and no Profiles there were a few
problems :-) )
So you could test Autoupdater now - just launch your v2.0.0 and try to
update to 2.0.1
My update was successful (just don't accidently click on empty space in
RequiredMods - that bug was fixed in 2.0.1)

I will install a VM and change language to German here so I could catch
your Exception.

**Comment by Fragjacker** [comment]
# Testing and Suggestions
> So you could test Autoupdater now - just launch your v2.0.0 and try to
update to 2.0.1
My update was successful (just don't accidently click on empty space in
RequiredMods - that bug was fixed in 2.0.1)

Alright the autoupdater works just fine as I have just tested it. I however have a few suggestions:
- When updating to a new version, the old Mod Manager executable still remains. If you launch it via some old shortcut from your desktop it will launch the old version again instead the new one.
- When launching the old Mod Manager you can update it as often as you want 😀 .

So my suggestions are:

1. Delete the old Mod Manager executable after update.
2. Create a new shortcut of the updated version on the Desktop.

# Exception fix

Also I have looked into your code and debugged it and actually found the reason for the exception. The fix was quite simple. In your `SettingsManagerForm.cs` do the following changes:

In line 505 change to `inverseDeclinationCheckBox.Checked = Convert.ToBoolean(stringValue);`
And in line 511 change to `inversePanCheckBox.Checked = Convert.ToBoolean(stringValue);`

Previously you also been converting to int32 before going to bool which was the source of the issues. Apparently you can directly convert from the string `true` to type `boolean` without any intermediate conversions.

# App termination
Another thing I noticed when debugging was that `Application.Exit()` somehow does not properly shut down the application actually and I still got silent exceptions. I'd suggest that you use the following function to terminate the application instead. I tested it and it didn't produce silent exceptions on app closing:

```C#
/// <summary>
/// This function properly terminates the Application
/// </summary>
private static void TerminateApp()
{
    if (System.Windows.Forms.Application.MessageLoop)
    {
        // WinForms app
        System.Windows.Forms.Application.Exit();
    }
    else
    {
        // Console app
        System.Environment.Exit(1);
    }
}
```

**Comment by IgorTheLight** [comment]
Hm!
Interesting information!
I would do something with autoupdates. Most likely both things suggested by
you (delete old *.exe and update the shortcut if possible).
About Exception - if I wouldn't convert it to Int32 - it will crash on my
system. But if you would convert to Int32 - it will crash yours. That's
strange.
About strange Application termination - ok I will change it to your variant.
One more interesting thing is that I created a Virtual Machine, installed
Windows 10 there and changed everything to German and I couldn't reproduce
this problem. That is really strange.
Scheisse! :-)
Meanwhile I fixed a few regressions, so 2.0.1 will be all about small
bugfixes. You could update it once in a day so you could see progress.
Please update it from 2.0.0 because it can't be updated from 2.0.1 to 2.0.1
(there is no build number for now).

**Comment by IgorTheLight** [comment]
I implemented a new way of terminating a program!
Now I will try to wrap our strange Exception in a "try-catch" so it will
try to convert String to Boolean but if it fails - it will convert it to
Int32 first and then convert it to Boolean.
That is a temporary solution and will be changed in 2.0.2 (optimization
pass)

**Comment by Fragjacker** [comment]
> Now I will try to wrap our strange Exception in a "try-catch" so it will
try to convert String to Boolean but if it fails - it will convert it to
Int32 first and then convert it to Boolean.
That is a temporary solution and will be changed in 2.0.2 (optimization
pass)

Yes the infamous _"It works on my machine!"_ it's truly weird that the inbuilt Int32 conversion fails for me but not for you. Here's two alternatives that could work, since the conversion to Int first then boolean next is a bit weird and could be done in one line:

```C#
inverseDeclinationCheckBox.Checked = stringValue == "true";
````

Or be more sophisticated with more options:

```C#
public static class StringExtensions
{
    public static bool ToBoolean(this string value)
    {
        switch (value.ToLower())
        {
            case  "true":
                return true;
            case "t":
                return true;
            case "1":
                return true;
            case "0":
                return false;
            case "false":
                return false;
            case "f":
                return false;
            default:
                throw new InvalidCastException("You can't cast that value to a bool!");
        }
    }
}
```
I took those suggestions from here https://stackoverflow.com/questions/9742724/how-to-convert-a-string-to-a-bool

Both solutions should work and be machine independant.

**Comment by IgorTheLight** [comment]
Thanks for the info! :-)
And yes - it's not only works for you but doesn't for me - it also doesn't
work in a VM where EVERYTHING is in German (including data and Number
formats). And I don't even speak German! :-)
That's why testing is so hard sometimes.
So... does it work for you now? I will implement one of suggested solutions
for 2.0.2
Maybe even for 2.0.1 but I want to fix bugs first (if there still are
some...)
About "user-friendly interface" - maybe I should create a
ModManagerLiteForm where there will be MUCH less buttons. But there will
also be a button "Advanced mode" for Power Users, Programmers and all kinds
of Techpriests?
That will be just another Main Form - NOT a whole new program! :-)

**Review by Fragjacker — APPROVED** [review]
> Thanks for the info! :-)
And yes - it's not only works for you but doesn't for me - it also doesn't
work in a VM where EVERYTHING is in German (including data and Number
formats). And I don't even speak German! :-)
That's why testing is so hard sometimes.
So... does it work for you now?

Yes, I can confirm that the Settings window doesn't crash anymore. Also the language of my OS wasn't the cuplrit of this since the traceback clearly identified the `Convert.ToInt32()` as the cause of the crash because it apparently couldn't convert the word `"true"` into 1 and crashed for me. Why it didn't crash for you as well eludes me. Coding can be sometimes scary with those kind of weird bugs happening 😀 .

Now there's only the two conflicting files remaining that need to be resolved and we should be fine here for a merge!

**Comment by Fragjacker** [comment]
# Merge Request Approved
@IgorTheLight Alright! The latest changes are merged into master now and a new release has been made, yay!

# New Feature Idea
Also I have just had another idea for a new feature. I saw that you can set the game resolution to 4K in your settings window. However other people been trying this manually in the past and had issues with the fonts. My idea is that we could fix both the resolution _and_ the fonts via the mod manager easily with one click for any resolution!

Check this issue out here: https://steamcommunity.com/app/9450/discussions/0/792924952801763017
Plus the fixed fonts for 4K (This we could do programatically): https://drive.google.com/file/d/0BwFP08L2ToUzVkVrY2V4TUpoQzQ/view

**Comment by Fragjacker** [comment]
One tiny issue that I have found is that the `Find MISSIN` button doesn't work at all. It stays greyed out even if there is at least one mod marked as missing.

image

**Comment by IgorTheLight** [comment]
Ah yes!
I've been using a larger font for some time already (it even needed for
1920x1080).
I like the idea of enlarging the font for a bigger resolution!

**Comment by IgorTheLight** [comment]
Well... it works, maybe not super intuitively - you have to CLICK on a
missing mod so the button will activate! :-)
Yeah... probably not the most user-friendly idea!

**Comment by IgorTheLight** [comment]
I'm glad that 2.0.1 is finally out! :-)
My next plans:
* 2.0.2 - bugfixes (if there are some) and refactoring/optimizations (my
favorite part!)
* 2.1.0 - Automatic large font solution. Autoupdate feature (we have manual
update - so it's semi-automatic now). Maybe even a Light Main Frame (I told
you about that previously)
* Well - there are no plans for a long future. Maybe I could port it
(again) to .NET Core 3.0 - it's not like this is really needed or something
:-) Maybe port it to WPF instead of WinForms so we could easily add custom
skins? Do we even need that?.. :-)

**Comment by Fragjacker** [comment]
# New Features
Alright I have implemented the cleanup of the old executable once a new one got downloaded. On top of this a new shortcut is created that points to the new version of the DoW Mod Manager in commit 64ec9080bd1ac98e0e3d8f8eac2b909bd6d1e934. I dubbed it 2.0.2 as of now. I also switched the download location of the executable to the main repository so that all is centralized for future app updates in commit 6dcb36955eb50032e063f4e02d3e4d900c07fb59.

**Pull request merged**
