### PR TITLE
I merged 1.5 to master branch, refactored some code and upgraded .NET Framework from 4.5 to 4.5.2

### PR DESCRIPTION
**Pull request by IgorTheLight**
- Added changelog for 1.52
- Merged from 1.5 to master branch
- Refactored some code (deleted/commented some unused code, renamed a few variables, added a few "using FileStream" and so on)
- Upgraded from .NET Framework 4.5 to 4.5.2 A lot of small improvements and now I could (and I did) use EnableWindowsFormsHighDpiAutoResizing  Sadly it didn't do much. I googled - found nothing useful on that option. But it's enabled now.
That pull request is not that big that the last one. But it didn't break anything. I hope :-)

### CODE REVIEW

**Comment by Fragjacker** [comment]
@IgorTheLight Auto merge is not possible because the README.md file is conflicting. Fix this on your local branch so I can auto merge without conflicts please. Meanwhile I will test the stuff you did so far 👍

**Comment by IgorTheLight** [comment]
I tried to resolve it. Is it working now?
(I added myself to 1.53 changelog. If you don't like it - you may just
delete it)

**Comment by IgorTheLight** [comment]
I know why this problem occurred:
* I created version 1.53 yesterday and did a pull request
* Today I created version 1.54 (on the same branch - master) but didn't
make a pull request (there is no need for that)
* I didn't know that I can't touch the same branch where I did a pull
request from. So now it has changes even from 1.54 (that I didn't mean to
send you yet!)
I'm new to GitHub - I'm sorry :-)
I will revert changes to my master so it will be just like after I created
a pull request.
Next time I will create pull requests from different branches - my bad :-)

**Review by Fragjacker — APPROVED** [review]
@IgorTheLight I can confirm the merge conflict was resolved as well as the issues that I have reported! I am also fine with adding your name to the changelog, as I am actually quite happy that someone picked this app up and did some fixes to it 😀

**Comment by Fragjacker** [comment]
Merged!

**Comment by Fragjacker** [comment]
@IgorTheLight Also fixed some tiny issues with the README.md file after the merge. Make sure to pull the latest changes just in case.

**Comment by IgorTheLight** [comment]
Thanks very much! :-)
Let me look at what you have...
As I was expecting - you now have 1.54 but with README.md from 1.53 (I
covered t in my previous e-mail)
Nothing scary - just a few changes :-)
Just change your README.md in this way:
Line 2:
# DoW-Mod-Manager-1.54
Line 76-81:
## Version 1.54 (by IgorTheLight):

- I did all the changes that I found in article "High DPI support in
Windows Forms" written by Microsoft
- Upgraded .NET Framework from 4.5.2 to 4.7.2
- Added DPIAwareness is app.config
- Uncommented Windows 10 support in app.manifest

No more surprises - I promise! :-)

**Comment by IgorTheLight** [comment]
It looks ALMOST perfect now!
Just a small adjustment to README.md:
>>>>>
# Changelogs

## Version 1.54 (by IgorTheLight):

- I did all the changes that I found in article "High DPI support in
Windows Forms" written by Microsoft
- Upgraded .NET Framework from 4.5.2 to 4.7.2
- Added DPIAwareness is app.config
- Uncommented Windows 10 support in app.manifest

## Version 1.53 (by IgorTheLight):

- Upgraded .NET Framework from 4.5 to 4.5.2 - a lot of small improvements.
But also that will add "EnableWindowsFormsHighDpiAutoResizing" feature in
app.config
- Enabled feature stated above
- Code refactoring - a lot of small tweaks here and there. More "C#
friendly" variable names
>>>>>
Now it will be perfect!
Next time I will be more careful with pull requests! And definitely NOT to
make them in master branch! :-)

**Comment by IgorTheLight** [comment]
About Mod Manager - I used it from version 1.2 and liked it very much. And
still do!
Now it's even better! I hope I didn't introduce any new "unexpected
behaviors" :-)

P.S. Just don't forget to update README.md then I will sync with your
version.

**Comment by Fragjacker** [comment]
@IgorTheLight Updated the readme file now proper. Also welcome to Github 😀 ! We're all here to learn something new everyday 😁 . Glad you like my Mod Manager as well! I also tested it and it worked all proper so far, no new bugs introduced that weren't there in the first place 😬 .

**Comment by IgorTheLight** [comment]
Nice!
Thank you for your patience :-)
If I could do something useful with it - I will let you know!

**Pull request merged**
