### PR TITLE
Small changes (mostly mods updates)

### PR DESCRIPTION
**Pull request by IgorTheLight**

### CODE REVIEW

**Comment by Fragjacker** [comment]
It's been a while since I've seen you, good you're still around 😀.

**Comment by IgorTheLight** [comment]
I'm still alive :-)
Glad to hear from you too!

**Review by Fragjacker — CHANGES_REQUESTED** [review]
I see the the mod version is 2.1.2 though I have pushed a small update in the past to put the mod to 2.1.3 so make sure you merge the latest changes proper so we don't go back in the version number.

**Comment by IgorTheLight** [comment]
But... I did that!
Didn't I?

**Comment by IgorTheLight** [comment]
My "master" branch is synced with 2.1.3 - https://github.com/IgorTheLight/DoW-Mod-Manager
You may check it.
Very strange...

**Review by Fragjacker — COMMENTED** [review]
Have a look at commit ef05b4f873e8e307d24780b635eda070b1ffe7bd. The files in this pull request are all faulty since it shows version 2.1.2 which is outdated. So I don't know what happened here but those are definitely bad changes. Maybe something went wrong with the pull request creation.

**Comment by IgorTheLight** [comment]
Looks like a bug.
Could you just take my "DoW Mod Manager Download Mods.list" and "version"
files - that's all that I modified since your 2.1.3
Sorry for adding some problems :-)

**Review by Fragjacker — APPROVED** [review]

**Comment by IgorTheLight** [comment]
Thanks!
Now you have the latest mods :-)

**Pull request merged**
