### PR TITLE
DoW Mod Manager 2.3.2.0 update after a year xD

### PR DESCRIPTION
**Pull request by IgorTheLight**
- Fixed unnecessary cast in method that searches for videodrivers. That may fix some rare issues with videocard detection
- Fixed a bug where Mod Manager would crash if you click on "Open folder..." button if you don't have any mods installed
- Sealed two classes for performance gain
- Changed StringBuilder + File.WriteAllText to a simple and more efficient StreamWriter
- Created new class - "extensions" and refactored GetValueFromLine() method to an extension
- Renamed a few variables here and there

### CODE REVIEW

**Comment by IgorTheLight** [comment]
Merry Christmas, FragJacker! ;-)
I hope you are doing well! I did a few small tweaks here and there.
I saw another pull request so now you have even more work to do! xD

**Comment by Fragjacker** [comment]
Well it's been a while but here we go! Though what's with all those Mergeconflicts again oof. 😭

**Comment by Fragjacker** [comment]
Weird, I just grabbed this pull request locally and was able to rebase `master` into it, which means there was indeed missing stuff but no actual merge conflicts during rebase so that is weird. You may also want to consider adding a fix to #36 into this merge as well.

**Comment by IgorTheLight** [comment]
> Weird, I just grabbed this pull request locally and was able to rebase master into it, which means there was indeed missing stuff but no actual merge conflicts during rebase so that is weird. You may also want to consider adding a fix to https://github.com/Fragjacker/DoW-Mod-Manager/issues/36 into this merge as well.

GitHub is always been this weird xD
I will fix https://github.com/Fragjacker/DoW-Mod-Manager/issues/36 so wait for it ;-)

**Comment by IgorTheLight** [comment]
Oh shit! I already have 2.3.2.0 released (with tags and all that). So I will make a small bugfix release 2.3.2.1 ;-)

**Comment by IgorTheLight** [comment]
Hm... The whole Autoupdate is in another Thread already - that's why I didn't changed anything before.
(MoDManagerForm.cs, from line 198):
            if (settings[AUTOUPDATE] == 1)
            {
                new Thread(() =>
                {
                    DialogResult result = DownloadHelper.CheckForUpdates(silently: true);

                    if (result == DialogResult.OK && settings[AOT_COMPILATION] == 1)
                        settings[ACTION_STATE] = (int)Action.CreateNativeImage;
                }
                ).Start();
So it's not on the main Thread already, right?

**Comment by IgorTheLight** [comment]
Judging by the look of the problem - maybe it's better to test and publish 2.3.2.0 first? ;-)
I found why that problem occurs and it may take some some time to find an elegant solution to the problem xD

**Comment by IgorTheLight** [comment]
Hi!
Is everything ok? When you have free time - please, publish a 2.3.2.0 release so people would see that project is not abandoned ;-)

**Comment by Fragjacker** [comment]
I am quite busy during the week so I hope I can find some time during the weekend to finally push this oof.

**Comment by IgorTheLight** [comment]
Ok, I understand ;-)
Take care!

**Comment by Fragjacker** [comment]
I finally managed to merge this bad boi into master xD. There were lots of weird merge conflicts when I merged my master branch into your pull request but those were rather small and I wonder where they came from. Either way it's done now 😄 .

**Comment by IgorTheLight** [comment]
Nice! xD
As usual - sorry for inconveniences ;-)

**Pull request merged**
