### PR TITLE
1.8.1 is here! Smaller EXE and a few optimizations!

### PR DESCRIPTION
**Pull request by IgorTheLight**
I think it's still worth the update!
Also added disclaimer in README.MD that this application could be dangerous and we have zero responsibilities fort that! ;-)

### CODE REVIEW

**Comment by IgorTheLight** [comment]
You didn't merged the 1.8.0?
This is heresy! ;-)

**Comment by Fragjacker** [comment]
Well I just skipped 1.8.0 and merged 1.8.1 right away 😀 . Also one thing I noticed is that this may collide with the `-nomovies` option:

image

-nomovies disables the intro movies, that are played when starting the game. So there may be a clash, unless that option refers to the stronghold movies, played in the campaign 🤔 . Other then that this is a _very_ cool feature!

Also when selecting the player profile it would be cool if the user could create a _new_ profile right from that window.
image
Since some people reported in the past that the game won't allow them to create a new profile if they start the game with a mod. So this could fix this!

Another suggestion would be to add tooltips/descriptions since some options may sound enigmatic like this one 
image
So the folks know what effect changing that and similar options has on the game.

**Comment by Fragjacker** [comment]
Also updated the README.md file with a new picture that shows the full glory of the DoW Mod Manager v1.8.1 😀 make sure you pull them latest changes!

**Comment by IgorTheLight** [comment]
Nice work!
Sorry for a small mess - I thought that you merged 1.8.0 before (you even
hinted at that). But that problem is over now so it's fine :-)
What exactly disables NoMovies? I have to test that actually. But it's NOT
changing the "-nomovies" command - that I could assure you!
Ok, I will add the ability to create new Profiles from Settings Manager.
Probably in 1.9.0
What "rl_sso_num_times_shown" does - I'm not sure. There is only that
information and it's about DoW2:
https://community.dawnofwar.com/discussion/8413/connecting-relic-account-to-steam
So it's related to the network and it shows a prompt? Something like that
:-) Maybe I should rename it to "Show login prompt" or something...
Did you saw how small DoW Mod Manager v1.8.1.exe is now ;-)
I updated the screenshots - they are glorious! :-)
I see that you have some Python + ML projects? Could I mess with them too?
:-) I'm not sure that I want to, but who knows!
Did you tried to compile Python code using Nuitka (for native performance)?
python -m pip install nuitka
And then create an EXE with:
python -m nuitka --standalone your_main.py
If you don't want to include dependencies:
python -m nuitka  your_main.py
You probably know all of that already :-)

**Comment by Fragjacker** [comment]
> What exactly disables NoMovies?

It disables the intro movies when starting up the game.

> Did you saw how small DoW Mod Manager v1.8.1.exe is now ;-)

That is indeed very cool. What was the culprit of it being so big? To many imports?

> I see that you have some Python + ML projects?

Yeah you probably refer to that p-grad-CAM repo which is basically my Master Thesis project. Feel free to fork it. Though I have ran a profiler on the code and the majority of time is wasted on Tensorflow library functions. 

However I have also have other Python projects too, which are yet private and unreleased, which could indeed benefit from nuitka, since I am using pyinstaller for them as of now. Will take a look at nuitka! Native performance is always appreciated 😁 .

**Comment by IgorTheLight** [comment]
"What exactly disables NoMovies?" - my bad - I mean "Watch Movies". I
tested it and it does nothing (again - I mean "Watch Movies" option). If
you turn it off - game will start and turn it on. So I think that's some
kind of left-over. If you are curious - it's "force_watch_movies=1" in
Local.ini
Why DoW is much smaller now? That's because every Form created it's own
copy of Icon resource. Let's count how many copies were there:
* One copy for the EXE
* One copy for the ModManager
* One copy for the ModMerger
* One Copy for the ModDownloader
* One copy for the SettingsManager
So how to fix that? Read Second answer (with 49 upvotes):
https://stackoverflow.com/questions/189031/set-same-icon-for-all-my-forms
Yep - one line of code!
Of course you have to delete this.Icon = <something> in every FormDesigner
and also delete *.resx file (where Icon copy is stored).
So now the source folder is lighter AND *.exe is lighter AND it uses a
little bit less RAM ;-)
About your Python projects - I will look at them someday. Depends on my
mood - I am a very lazy person ;-)
So what are my plans for DoW?
1.8.2 - more optimizations (probably some Regex vs string.Contains() tests)
+ a few tweaks to SettingManager (suggested by you)
1.9.0 - Search for ModDownloader (your suggestion) + TimerResolution
changer (good for weak CPU's but bad for laptop battery life) + mod loading
errors showing (your suggestion)
About Python - make sure that you are using CV2 instead of CV (if you use
it somewhere) and test some Nuitka building :-) If that would fail - try to
build some simpler applications first (like Calculator or something like
that)
So use:
import cv2
You will have to change a few lines of code here and there but it's worth
it!

**Comment by Fragjacker** [comment]
Finally got Nuitka to work on my device 😀 . So far it produces a bigger executable then pyinstaller but also shows slightly better performance right off the bat. Guess it grabs more libraries and packs them into the standalone 🤔 .

**Comment by IgorTheLight** [comment]
You could try this experimental feature - it will grab less modules:
python -m nuitka --standalone --experimental=use_pefile your_main.py

**Pull request merged**
