### PR TITLE
2.0.4 is here! "You requested a psyker, My Lord?"

### PR DESCRIPTION
**Pull request by IgorTheLight**
## Version 2.0.4:

- Optimization: added ability to use AOT compiler - the fastest way to execute .NET application! 557 ms and 9788 Kb of RAM (default singlethreaded JIT compilation) vs 432 ms and 9876 Kb of RAM (Multithreaded JIT compilation) vs 363 ms and 6316 Kb of RAM (AOT compilation)
- Added ability to disable Multithreaded JIT compilation in DoW Mod Manager.ini and in AboutForm
- Added ability to disable autoupdates in DoW Mod Manager.ini and in AboutForm
- "Active Videocard" option in SettingsManagerForm now shows user's videocard name instead of a number
- Deleted all unused code and added descriptions to all methods in ModDownloaderForm
- Added descriptions to all methods in SettingsManagerForm
- Optimization: all checkboxes and trackbars are not triggered when initialized (in SettingsManagerForm) - it's x1.2 times faster! 42.7 ms vs 51.1 ms
- Optimization: changed string to StringBuilder() in SaveButton_Click() method  (in SettingsManagerForm) - it's x1.125 faster! 4.0 ms vs 4.5 ms
- Optimization: changed string to StringBuilder() in ModManagerForm_Closing() method  (in ModManagerForm) - it's x1.09 faster! 4.3 ms vs 4.7 ms
- OPTIMIZATIONS string constant was renamed to DOW_OPTIMIZATIONS for less confusion
- If AOT compilation is enabled - application will be re-optimized after an update!
- Added an new method for getting a setting from settings Dictionary in ModManagerForm

### CODE REVIEW

**Comment by Fragjacker** [comment]
@IgorTheLight I have done a little bit of research and found .NET Native which uses AOT compiler to translate .NET into antive machine code instead of Intermediate Language (IL). Maybe it's worth some further investigation if even more performance improvements can be gained using .Net Native unless you have done that already 😁 . Check this article out https://docs.microsoft.com/en-us/dotnet/framework/net-native/

Besides of that I will check out and review this pull ASAP.

**Comment by Fragjacker** [comment]
Also the merge conflicts are getting out of hand. Make sure you merged my master branch into yours and resolve the merge conflicts proper. I suggest using in situ apps like Meld or KDiff via command lines or similar.

**Comment by Fragjacker** [comment]
Other then that I recently wanted to give 4K resolution a try but it doesn't work for me. It just resets the resolution back to 800x600 each time I start the game and try to go beyond 1920x1080. The resolutions below that work but not 2K and 4K 😭 .

**Comment by IgorTheLight** [comment]
Oh thanks!
But sadly it's only for UWP (Universal Windows Platform - Windows Store)
programs :-(
https://stackoverflow.com/questions/32607689/how-to-use-net-native-in-winform-and-c-sharp-visual-studio-2015
Maybe we could use it when .NET 5 comes out.

**Comment by IgorTheLight** [comment]
Maybe that's an engine limitation? I just assumed that DoW may run in any
resolution but maybe that's not true. I'm not sure that I have to delete 2K
and 4K options but if that will not  for a few more people - I would!
About merge conflicts. You will not like that idea but... may you just
download my master as *.ZIP and unzip it in your folder? It's like 30
seconds. I didn't add any malicious code in DoW Mod Manager ;-)
Resolving it in a "proper way" may take 20-30 minutes. Do we really have to
check every line of code?
Let's say I changed something that you didn't like - you may "checkout" a
previous commit and your code will be fine :-) There are only two
contributors - it's not like we will brake anyone else's code (kids, please
don't do that at home!)

**Comment by Fragjacker** [comment]
Well the issues have to be addressed at some point. Just copypasting your files over mine without further inspection could nuke potential changes and just going one commit back would nuke your changes in return 😀 . I gotta maybe do the merge tomorrow or so for you but then make sure to apply the latest master branch from my repo onto yours.

Reason being that if you don't update it I'll keep getting the same issues over and over for each new pull request you do piling up higher and higher. Once you applied the my laters master onto yours I'll only have to fix merge conflicts from that commit in time, instead of the X commits behind the last time you updated your master branch from my repo 😁 .

**Comment by IgorTheLight** [comment]
Ok. I will check your changes. I hope there are not many of them...
That's really tedious even if I can see the diffs. Or maybe I'm just lazy
:-)

**Comment by IgorTheLight** [comment]
I checked the difference between my master and your master - yep! I want
those changes in 2.0.4 Nothing suspicious!
It's just too many changes for poor GitHub to handle :-) You could ask
about any change if you want to (just copy the code or say where it's
situated)

**Comment by Fragjacker** [comment]
Alright today I won't have time to merge this but hopefully tomorrow 😬 .

**Comment by IgorTheLight** [comment]
It's fine :-)

**Comment by Fragjacker** [comment]
Alright I merged plus did some small changes to the checkboxes changing them to radio buttons as this simplifies the activation/deactivation code as radio buttons only allow one selection at a time anyways.

Make sure you update your master branch with the latest goodies 😀 .

**Comment by IgorTheLight** [comment]
Thanks!
That was a leftover, because you TECHNICALLY could use both optimizations
at the same time. But if you do so - application will run slow ("cold
start" but after that it will just use AOT and be fast). So:
* Multoothreaded JIT - first start is slow (but still a little bit faster
than Singlethreaded), all starts after first are faster.
* AOT - first and all other starts are fast and application is faster than
before.
* MultiJIT + AOT - first start is slow (because of a JIT Compilation) but
others are fast (because it will use AOT). So you just make your first
start slow and gain nothing. That's why I disabled the feature to use both
of them at the same time.
Thanks for making it more convenient :-) I will sync my master with yours.

**Comment by IgorTheLight** [comment]
I added 2.0.5 to my Releases.
Please sync it with your master because I added changelog (in *.txt and in
AboutForm). Also I fixed a few comment typos.
My plans for 2.1.0:
* Add Large Font support
* Update Ultimate Apocalypse mod to 1.88.742 -
http://www.mediafire.com/file/r74491ydd07p3tf/Ultimate_Apocalypse_Patch_-_188742.zip/file
* Update .NET Framework to 4.8 The reason for that is that 4.7.2 and 4.8
have the same OS requirements (Windows 7 - Windows 10) and 4.8 was included
by default in Windows 10 Update 1903
A few controversial changes:
* Delete changelog for 2.0.0 - 2.0.5 and replace it with a GitHub link to a
changelog.txt
* Delete version number and "Written by FragJacker" in ModMergerForm. The
reason for that is that we have a proper AboutForm with all information
about authors and our application is monolithic and we can't update one
Form but not others.
* Add emails for authors. I would give this email - igorthelight@gmail.com
What would be yours (if you want to give one)?

**Comment by Fragjacker** [comment]
> I added 2.0.5 to my Releases.
Please sync it with your master because I added changelog (in *.txt and in
AboutForm). Also I fixed a few comment typos.

I pulled your latest changes into my branch.

> * Add Large Font support

I think different resolutions require some hex editing of core game files. Take a look at this repo here: https://github.com/zero334/Dawn-of-War-Widescreen-Fix

> * Delete changelog for 2.0.0 - 2.0.5 and replace it with a GitHub link to a
changelog.txt
* Delete version number and "Written by FragJacker" in ModMergerForm. The
reason for that is that we have a proper AboutForm with all information
about authors and our application is monolithic and we can't update one
Form but not others.

I agree since this has became a multicollabarion project now and credits are sorter differently now. Especially like the changelog.txt on github. I think we should go the same route with the file that contains the download links when attempting to download mods. That would make updating them _much_ easier. Currently we have to do a minor release so that the app autoupdates with the inbuilt text definitions, which is problematic.

> * Add emails for authors. I would give this email - igorthelight@gmail.com
What would be yours (if you want to give one)?

My Email is littered enough with Emails already 😛 . I think just linking this repository should be enough.

**Comment by IgorTheLight** [comment]
About fonts - I remember there were the config-like files with font sizes -
no Hex editing needed! I will check that tomorrow!
About mod download information in a separate file - yes I will add that too
in 2.1.0
May you ask the creators of those active mods to add a link to a DoW Mod
Manager?
* https://www.moddb.com/mods/ultimate-apocalypse-mod - you know those guys
;-)
* https://www.moddb.com/mods/eranthis-project - ex-UA member
* https://www.moddb.com/mods/unification-mod-dawn-of-war-soulstorm - a big
combining mod
* https://www.moddb.com/mods/corncobmans-fun-mod-for-soulstorm - very
active mod
* https://www.moddb.com/mods/imperial-fists - a NEW mod. Yes -  a new one!

**Comment by Fragjacker** [comment]
> About fonts - I remember there were the config-like files with font sizes -
no Hex editing needed! I will check that tomorrow!

The hex editing was done for unlocking additional resolutions. The font size fix was I guess needed if someone set their _system_ resolution to 4K. As setting the game via the local.ini to 4K doesn't work, the game just resets to 800x600 default resolution. My theory was that it _may_ be possible to adapt the resolution hack to unlock true 4K resolution from the game itself.

> Any chance you can add support for 16:10 resolutions?

One guy requested the addition of 16:10 resolutions such as 1900x1200 and similar I think this would make a fine addition to our feature collection.

> May you ask the creators of those active mods to add a link to a DoW Mod
Manager?

I know the unification team _very_ well. In fact there may be a new release soon which will include the latest Mod Manager inside the installer (that I will create as I have the technology) plus hosting it on their page. The imperial fists mod is also no news for me as I pretty much am in touch with all the big boys of the modding community. There's a lot more new mods in the pipe too so we may need to add more in the future.

Hence having a separate file for mod links would be indeed of virtue.

**Comment by IgorTheLight** [comment]
I will investigate unlocking additional resolutions.
Adding 16:10 would be not hard (theoretically).
Nice news about new mods! I will add a separate file for easier handling of
mods.
Also - you could play around with my last version:
https://github.com/IgorTheLight/DoW-Mod-Manager/raw/master/DoW%20Mod%20Manager/LatestStable/DoW%20Mod%20Manager.exe

**Comment by IgorTheLight** [comment]
Hi!
I've added a few most common 16:10 resolutions, made most Forms resizable,
added the ability to read external modlist file (and ability to update it
automatically).
Never got the time to add large fonts. There are no problems - just didn't
have time for that.
Changes so far:
## Version 2.1.0 (Work in progress):

- Added a new mod to download for Dark Crusade - Cinematic Battles (Version
1.5)
- Ultimate Apocalypse mod was updated from 1.88.731 to 1.88.742 (with a new
Titan!, bugfixes and balance changes!)
- Added a few popular 16:10 resolutions
- ModDownloaderForm could be resized and maximized now
- SettingsManagerForm could be resized and maximized now
- Modlist for ModDownloaderForm is stored in an external file now and could
be modified by the user!
- Modlist for ModDownloaderForm can be updated from GitHub automatically!
- Old version of DoW Mod Manager could be automatically deleted while
autoupdating even if it was renamed by the user
- Updated .NET Framework from 4.7.2 to 4.8 (the last version)
- Changelog now has only information about the last version with a link to
a full changelog on GitHub
- Added ability to enable Singlethreaded JIT compilation - a default
setting for .NET Framework applications
- Added a few new Actions and streamlined the code
- Deleted author and version number in ModMergerForm (with a permission
from FragJacker)
- Increased SettingsManager Form size a little bit for better readability
- All dialogBoxes will have title bars (even if title is empty)

I think we have to release this version soon so we don't get "feature
creep". Too many changes is also much harder to test!

**Pull request merged**
