### PR TITLE
2.0.2 Purging xenos

### PR DESCRIPTION
**Pull request by Fragjacker**
# Features
- Added the new feature that the old outdated executable is deleted, once a new version was retrieved.
- After the new DoW Mod Manager was downloaded, a new shortcut is created to it on the user desktop.

## How to Test:
Type the following commands into the command line tool of choice:
```
git fetch origin pull/5/head:NEW_BRANCH_NAME
git checkout BRANCH_NAME
```
After one is done delete the branch again
`git branch -D BRANCH_NAME`

### CODE REVIEW

**Comment by Fragjacker** [comment]
@IgorTheLight Maybe have a look at this bad boi here? 😀

**Comment by IgorTheLight** [comment]
I will look at it tomorrow!
Sounds interesting! I (on the other hand) implemented a few interesting
things myself:
My 2.0.2 version:
- If there is a missing mod - it will be selected so user could easily find
it
- All code has been refactored (where needed)
- Optimization: refactored GetLoadedMods() method in ModMergerForm - it's
x1.15 times faster! 0.86 ms vs 0.99 ms
- Optimization: JIT compiler uses Profiler so it could use multiple threads
now - ModManagerForm starts x1.27 times faster! 434 ms instead of 550 ms
- In ModMergerForm Mod.State is an enum now instead of a string. That may
increase some operations and reduce memory usage
- There is no more storing an unnecessary reference to a new Form when it's
been created
- Added annotations for all methods in ModManagerForm
- Small optimizations here and there

So I will check your 2.0.2 and merge them :-)

**Review by IgorTheLight — APPROVED** [review]
It's working quite good. Just delete the duplication of starting a new program twice and trying to terminate old one twice:
        private void Completed(object sender, AsyncCompletedEventArgs e)
        {
            ThemedMessageBox.Show("Download completed!\nApplication will restart to take effect", "Good news!");

            CleanupAndStartApp();
        }

**Comment by Fragjacker** [comment]
> It's working quite good. Just delete the duplication of starting a new program twice and trying to terminate old one twice:

Strange. Maybe you got bamboozled by the web UI? My actual code only has one call to `CleanupAndStartApp()`:
```C#
private void Completed(object sender, AsyncCompletedEventArgs e)
{
    ThemedMessageBox.Show("Download completed!\nApplication will restart to take effect", "Good news!");
    CleanupAndStartApp();
}
```

Also in that function there's only one call to close the old app and one call to open the new app 🤔 .
```C#
private void CleanupAndStartApp()
{
    // Start new downloaded exectuable
    Process.Start(executablePath);
    // Delete the old executable after 3 seconds have passed using cmd!
    Process.Start("cmd.exe", "/C choice /C Y /N /D Y /T 3 & Del \"" + oldexecutablePath + "\"");
    CreateShortcut($"DoW Mod Manager v{latestStringVersion}");
    ModManagerForm.TerminateApp();
}
```
Other then that I am thinking about implementing and automatic check for an update when starting the app. If there's a new update available the user gets a prompt asking him if he wants to update now or not.

**Comment by Fragjacker** [comment]
Closing this pull request to merge the latest of @IgorTheLight changes into my own ones. There will be a new request.

**Comment by IgorTheLight** [comment]
Hm, ok!
My 2.0.2 + your 2.0.2 looked fine to me :-)
My current 2.0.2 release is just that: my 2.0.2 (optimizations) + your
2.0.2 (delete old file + create new *.lnk)
I will write my 2.0.3 which will be more optimizations. Then I will merge
it with your 2.0.3
I think it's not a bad idea - we are making two parts of one update! :-)
About autoupdater - yes, that's a good idea!

**Pull request closed without merging**
