### PR TITLE
v2.0.3 "Reinforcements have arrived!"

### PR DESCRIPTION
**Pull request by Fragjacker**
# Description
This is the pull request that contains @IgorTheLight 2.0.2 changes plus my 2.0.3 changes that contains the auto update function.

# Features
## v2.0.2

- If there is a missing mod - it will be selected so user could easily find it
- All code has been refactored (where needed)
- Optimization: refactored GetLoadedMods() method in ModMergerForm - it's x1.15 times faster! 0.86 ms vs 0.99 ms
- Optimization: JIT compiler uses Profiler so it could use multiple threads now - ModManagerForm starts x1.27 times faster! 434 ms instead of 550 ms (It has to improve calculation speed in all parts of application!)
- After downloading a new version, old version of DoW Mod Manager will be deleted and a new shortcut will be created on the user's Desktop (thanks, FragJacker!)
- In ModMergerForm Mod.State is an enum now instead of a string. That may increase some operations and reduce memory usage
- There is no more storing an unnecessary reference to a new Form when it's been created
- Added annotations for all methods in ModManagerForm
- Small optimizations here and there

## v2.0.3
- Added a query on startup to ask the user to update the application if a new version is available.
- Added code to create a new shortcut of the updated DoW Mod Manager version on the desktop after the application update has succeeded.
- Added the feature that the old DoW Mod Manager version will be deleted after the update has finished.
- Refactored code for easier access internally.

# How to Test
Type the following commands into the command line tool of choice:
```
git fetch origin pull/5/head:NEW_BRANCH_NAME
git checkout BRANCH_NAME
```
After one is done delete the branch again
`git branch -D BRANCH_NAME`

### CODE REVIEW

**Comment by Fragjacker** [comment]
Alright @IgorTheLight care to review this pull request? It should have both your and my changes properly merged and ready to go into master.

**Comment by IgorTheLight** [comment]
Ok. I will merge it with my 2.0.3 and test it!
My new version just has one small tweak:
- Optimization: changed modlist.Add() to a proper List initialization - it's x1.04 times faster. Yay? 2.7 ms vs 2.8 ms. At least it looks cleaner now.

**Review by IgorTheLight — APPROVED** [review]
It works nice!
I just did a few small changes (check my "master" branch)
Or I may create a pull request (that sounds messy ;-))

**Comment by IgorTheLight** [comment]
There is just one small complain - new features in a bugfix release.
I wanted 2.0.X releases to be bugfix and refactorings only. But we are pushing new features here.
It's not a big deal here, but in future it may be a bad habit ;-)

**Comment by IgorTheLight** [comment]
My plans for a near future:
- Move silent autoupdate to a new thread. I will test will it be faster that way
- Keep looking at already existing code and try to optimize something
- Add ability to enlarge fonts when needed
When Visual Studio 16.7 will be released I will port DoW Mod Manager to a .NET Core 3.1 + WinForms. That will be on a separate branch "dotNet Core". The reason for that is my curiosity ;-) And that may be beneficial in a few ways: .NET Core is Open Source, it's crossplatform, it's faster, it's newer and it's evolving (.NET Framework is on a maintenance now).

**Comment by Fragjacker** [comment]
> There is just one small complain - new features in a bugfix release.
I wanted 2.0.X releases to be bugfix and refactorings only. But we are pushing new features here.
It's not a big deal here, but in future it may be a bad habit ;-)

Yes that is fair, however I _really_ wanted this auto updated utility in the Mod Manager as fast as possible. So forgive me my sins 😀 .

Another thing I noticed with the `Fetch MISSING` button is that you get no result if the missing mod does not exist in your reference file. Maybe some prompt would be due here to inform the user that the mod was unknown.

> My plans for a near future:
    - Move silent autoupdate to a new thread. I will test will it be faster that way
    - Keep looking at already existing code and try to optimize something
    - Add ability to enlarge fonts when needed
    When Visual Studio 16.7 will be released I will port DoW Mod Manager to a .NET Core 3.1 + WinForms. That will be on a separate branch "dotNet Core". The reason for that is my curiosity ;-) And that may be beneficial in a few ways: .NET Core is Open Source, it's crossplatform, it's faster, it's newer and it's evolving (.NET Framework is on a maintenance now).

I definitely support moving the autoupdate feature to a separate thread. As of now the autoupdater blocks the Form from showing up which is not intended.

The enlarge font feature would also _dramatically_ help people who want to play DoW in 4K resolution but get a font the size of an ant.

# My Plans

- For the next major version I had envisioned the UI overhaul to resolve the cluttered mess of buttons we have right now. 
- Next would be marking mods as outdated if there's a newer version available then installed (Preferably via some text file hosted here on github. That would make updating it a lot easier). I have some unused color code to render the text (orange) for exactly this purpose somewhere.

**Comment by Fragjacker** [comment]
@IgorTheLight Make sure to pull the latest of the master since I found an issue as I forgot to update the assembly info and the updater was asking me after each update that there is a new updated available. It's fixed now.

**Comment by IgorTheLight** [comment]
Agree - I will add a prompt when MISSING could be resolved. - OK, Google!
Play "Destination unknown"! :-)
I like your plans so far!
But... will we stop after that or that is an ongoing project? We always add
"one last feature"
Well it works for now (our release model) so why change something! :-)

**Comment by IgorTheLight** [comment]
Ok, thanks!

**Comment by Fragjacker** [comment]
> Agree - I will add a prompt when MISSING could be resolved. - OK, Google!
Play "Destination unknown"! :-)
I like your plans so far!
But... will we stop after that or that is an ongoing project? We always add
"one last feature"
Well it works for now (our release model) so why change something! :-)

Well at this point the Mod Manager is a living organism of sorts where we add new stuff where we see fit 😀 . Gradually adding new features over the course of the development was the modus operandum from the get go of this app anyways 😬 .

**Comment by IgorTheLight** [comment]
Nice!
We will test all our new skills on DoW Mod Manager then :-)
Sadly most likely noone would sponsor our job - there are just a few loyal
DoW fans! https://steamcharts.com/app/9450#1y
Random thoughts: do you need any of VirtualBox VM's? I just configured
Windows 98 SE, Windows XP SP3, Windows 7 SP1 and Windows 10 (2004).
Not just lazily installed - fully tweaked and installed all needed for
almost any job (drivers, updates, VC++, .NET Framework, Java)
That's why I didn't do anything interesting for DoW Mod Manager for a few
days :-)

**Comment by IgorTheLight** [comment]
P. S. You forgot to update changelog.txt for 2.0.2

**Comment by Fragjacker** [comment]
> P. S. You forgot to update changelog.txt for 2.0.2

Funny since I actually updated the in-app changelog but not the changelog.txt file itself 😀 .

> Random thoughts: do you need any of VirtualBox VM's? I just configured
Windows 98 SE, Windows XP SP3, Windows 7 SP1 and Windows 10 (2004).
Not just lazily installed - fully tweaked and installed all needed for
almost any job (drivers, updates, VC++, .NET Framework, Java)
That's why I didn't do anything interesting for DoW Mod Manager for a few
days :-)

Not yet but good to know where I can get some, should the need arise 😁 .

**Comment by IgorTheLight** [comment]
Hello there! :-)
I have an interesting performance test for you!
SettingsManagerForm start time:

// multithreaded JIT - no, AOT - no
// 511 612 ticks or 51.1 ms - cold start
// 449 380 ticks or 44.9 ms
// 452 104 ticks or 45.2 ms

// multithreaded JIT - yes, AOT - no
// 460 392 ticks or 46.0 ms - cold start
// 120 066 ticks or 12.0 ms
// 129 683 ticks or 12.9 ms

// multithreaded JIT - no, AOT - yes
// 82 779 ticks or 8.3 ms - cold start
// 81 871 ticks or 8.2 ms
// 79 517 ticks or 7.9 ms

// multithreaded JIT - yes, AOT - yes
// 244 659 ticks or 24.5 ms - cold start
//  80 392 ticks or  8.0 ms
//  79 894 ticks or  8.0 ms

So: Singethreaded JIT compilation < Multithreaded JIT compilation < AOT
compilation < Native code (we don't have this option)

Default Python option is to Interpret the code - this is even slower than
singlecore JIT in C#!
But you can do a few things:
* Use a JIT compiler (using PyPy). Warning: only Python 2.7.13 and 3.6.9
(x86) are supported! 3.8.4 x64 will not work! But you are not losing much
:-) ZERO additional work required - PyPy just takes your *.py file and
instead of interpreting it - JIT compiles it (as C# and Java does). First
load of the program may be slower ("cold start" as in all JIT compilers)
* Use Cython - a more strict implementation of Python but it's more
performant. It translates your code in C, compiles it and then imports it
in your Python project as a module.
* Make a native executable (using Nuitka or alternative) - we already
talked about that.
* Radical alternative - just use Julia programming language! It's "a faster
Python". Technically it's not Python at all - but syntax is VERY similar :-)

**Comment by Fragjacker** [comment]
I have used Nuitka in one of my Python projects, though haven't witnessed that much of a drastic performance change. If you want to get your hands dirty I could invite you to one of my private repos, that contains an useful tool (not yet released) which could maybe need some performance improvements (Is written in Python 2.7). It needs to do a lot of file I/O operations and I am sure stuff could be done to work faster. 

If you are interested, tell me 😁 .

**Comment by IgorTheLight** [comment]
Oh! That sounds interesting!
But I have zero experience with Python 2. Is that library big? Do you
consider porting it to Python 3? (Python 2 officially is not supported
anymore so you will see less and less people willing to tinker with it).
Well, your library is private but still.
Maybe I will help to port it on Python 3 or even Cython? Can't guarantee
anything.
Can you tell me more? Is that your project? Forked? :-)
In exchange I will tell you that I'm planning to create "dotNET Framework
Optimizer" which could do a bunch of useful stuff with dotNET Framework
itself and with programs written in it.
Not MUCH but still a few useful things. You could do all of that today by
using different *.cmd scripts or in PowerShell. And no - my program will
not just launch Command Prompt with those commands ;-)

**Comment by IgorTheLight** [comment]
I have news about multithreaded Autoupdater and AOT compilation!
DowModManagerForm:
// Singlecore JIT compilation (Autoupdate is in the same Thread)
//   5 452 321 =   545 ms (Autoupdate=0)
// 10 553 435 = 1055 ms (Autoupdate=1)

// Multicore JIT compilation (Autoupdate is in the same Thread)
// 4 350 376 = 435 ms (Autoupdate=0)
// 7 828 059 = 783 ms (Autoupdate=1)

// Singlecore JIT compilation (Autoupdate is in a new Thread)
// 5 568 867 = 556 ms (Autoupdate=0)
// 5 682 794 = 568 ms (Autoupdate=1)

// Multicore JIT compilation (Autoupdate is in a new Thread)
// 4 354 217 = 435 ms (Autoupdate=0)
// 4 472 958 = 447 ms (Autoupdate=1)

// AOT compilation (Autoupdate is in a new Thread)
// 3 659 173 = 365 ms (Autoupdate=0)
// 3 679 265 = 368 ms (Autoupdate=1)

Autoupdates,  Multicore JIT compilation and AOT compilation could be
enabled/disabled now in DoW Mod Manager.ini!
There are a few rules:
* To disable all compilation-related optimization you have to set
"MultithreadedJIT=0" and "AOTCompilation=3"and "ActionState=1" (that means
"Delete Native Image" )
* To enable Multithreaded JIT you have to set "MultithreadedJIT=1" and
"AOTCompilation=0"
* To enable AOT you have to set "AOTCompilation=1" and "ActionState=2"
(that means "Create Native Image"). "MultithreadedJIT" doesn't matter in
this case
* AOT Compilation ignores Multithreaded JIT compilation
* Yes - DoW Mod Manager has a State Machine now! You may change state and
perform Action when you would like to (as a programmer, of course!)
Ability to disable Autoupdates will be added to AboutForm (today)
Ability to enable Compilation optimizations will be added later

**Comment by Fragjacker** [comment]
That's some pretty nice performance boosts right there. Auto-update in a new thread beats the same thread versions, which was kind of to be expected. I am a bit surprised by AOT beating JIT as I would expect the opposite to be true, since less work is required as stuff is only compiled when needed.

> Autoupdates,  Multicore JIT compilation and AOT compilation could be
enabled/disabled now in DoW Mod Manager.ini!

Guess it would be cool to have them as checkbox options in the mod manager itself so all the special rules can be directly implemented as code which would prevent anyone from breaking stuff and cry.

I also got a question today in Discord which could need some fixing:

> "Hi in the Mod Manager settings in the Video tab there is an option "Active Videocard" mines at 0 and the other options are 1, 2, 3. What does it mean?"

So what do these numbers indeed mean? A more verbose and self explanatory item here would be better I think to reduce confusion.

**Comment by IgorTheLight** [comment]
Hi! :-)
JIT compilation is almost real-time so it uses more RAM and needs more time
to calculate things "on the fly" while AOT compilation is done before
application starts so it will not need additional RAM and CPU cycles. It
may be a little bit different in different programming languages. Here is
the useful article:
https://devblogs.microsoft.com/dotnet/got-a-need-for-speed-net-apps-start-faster/
Yes - checkboxes are in the AboutForm now! You can switch the type of
compilation just in one-two clicks of a mouse!
Autoupdates could be disabled/enabled there too!

About "what Active Videocard means?" - this is an exposed option
"screenadapter=0" from Local.ini If you have more than one videocard (or
integrated + dedicated) you could try to switch it from 0 to 1 (or 2 if you
have 3 videocards) and it will use your another videocard. Does it work - I
don't know. I'm just exposing this option in Setting Manager so users could
play with it and see for themselves. That will not harm them or their PC in
any way :-) Maybe instead of numbers I would show actual videocard names
(sounds like a reasonable idea).

Also - 2.0.4 is almost ready! It's (almost complete) changelog:
- Optimization: added ability to use AOT compiler - the fastest way to
execute .NET application! 557 ms and 9788 Kb of RAM (default singlethreaded
JIT compilation) vs 432 ms and 9876 Kb of RAM (Multithreaded JIT
compilation) vs 363 ms and 6316 Kb of RAM (AOT compilation)
- Added ability to disable Multithreaded JIT compilation in DoW Mod
Manager.ini and in AboutForm
- Added ability to disable autoupdates in DoW Mod Manager.ini and in
AboutForm
- Deleted all unused code and added descriptions to all methods in
ModDownloaderForm
- Added descriptions to all methods in SettingsManagerForm
- Optimization: all checkboxes and trackbars are not triggered when
initialized (in SettingsManagerForm) - it's x1.2 times faster! 42.7 ms vs
51.1 ms
- Optimization: changed string to StringBuilder() in SaveButton_Click()
method  (in SettingsManagerForm) - it's x1.125 faster! 4.0 ms vs 4.5 ms
- Optimization: changed string to StringBuilder() in
ModManagerForm_Closing() method  (in ModManagerForm) - it's x1.09 faster!
4.3 ms vs 4.7 ms
- "OPTIMIZATIONS" string constant was renamed to "DOW_OPTIMIZATIONS" for
less confusion
- Added an new method for getting a setting from "settings" Dictionary in
ModManagerForm
- Work In Progress: I'm adding an ability to re-optiimize application after
installing a new version using Autoupdater (ngen install "DoW Mod Manager
2.0.4.exe")

**Pull request merged**
