### PR TITLE
1.8.2 is out! This is the biggest optimization patch

### PR DESCRIPTION
**Pull request by IgorTheLight**
- Renamed "rl_sso_num_times_shown" to "Login Attempts" for more clarity
- Removed "Force Watch Movies" setting because it's effect was not proved. "-nomovies" is working as usual
- Optimization: changed Regex to String.Contains() in IsModRequired() method - it's 170x faster! 0.2 ms vs 34 ms
- Optimization: changed Regex to String.Contains() in GetActiveModsFromFile() method - it's 126x faster! 0.3 ms vs 38 ms
- Optimization: changed Regex to String.Contains() in GetModFoldersFromFile() method - it's 34x faster! 1 ms vs 34 ms
- Optimization: changed Regex to String.Contains() in ModIsPlayable() method - it's 10x faster now! 3 ms vs 32 ms
- Optimization: changed Directory.GetFiles() to File.Exists() in GetCurrentGameEXE() method - it's 1.45x faster now!
- Optimization: changed Directory.GetFiles() to File.Exists() in CheckForGraphicsConfigEXE() method - it's 1.45x faster now!
- Optimization: refactored StartGameWithOptions() method - it's 1.14x faster 
- Optimization: refactored GetMods() method - it's more readable and around 2% faster
- Optimization: There is no more Regex object calls in ModManager Form - it uses 35% less RAM now. 8388 Kb vs 11 300 Kb (in my case)
- Optimization: Startup time is 8% faster now - 512 ms vs 555 ms in 1.8.1 (with a lot of mods)
- Optimization: Application is a 1 Kb lighter. 1037 Kb vs 1038 Kb in 1.8.1
- Some small tweaks here and there

I have nothing against Regex. It could be useful in some situations but not in DoW Manager - all tests shows that they are slower in our cases.

### CODE REVIEW

**Comment by Fragjacker** [comment]
Oh that's some nice optimization changes right there! Guess ReGex was indeed overkill in this situation where I really only wanted to know if a word exists in a string or not. Gotta review this ASAP!

**Comment by IgorTheLight** [comment]
I'm glad to hear that!
DoW Mod Manager is addicting - I keep thinking "just one new feature and I
will do something else" ;-)

**Comment by Fragjacker** [comment]
Alright the pull request got merged. Make sure you pull from my master though because I have made some slight changes to your files, restoring my function documentation. Those comments before the functions are placed there on purpose:
```C++
/// <summary>
/// Sample Summary.
/// </summary>
/// <param name="MyParam"></param>
/// <returns></returns>
```
They are the C# anology to [JAVADOC](https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html) function documentation which displays additional information when you hover over a function name in an IDE. So in the future please don't delet them 😀.

**Comment by IgorTheLight** [comment]
Oops!
I tried to delete the most obvious comments. Probably I went too far :-)
I will pull your version and build upon it. Also I will add the same for my
methods.

Off topic: do you have more fun with a Python or with a C#? Would you like
DoW Mod Manager to be ported to Python? Just some random thoughts - it's
not like I'm secretly working on that or something :-)
Another random thought: we have to add a license for DoW Mod Manager. I'm
sure that noone actually will steal it and start to make money off it but
still :-) Maybe something liberal like MIT, GPLv2 (maybe v3 but some people
don't like it - we have to investigate), or zlib . BSD is too liberal so
anyone could not only sell it but also make it close source so original
authors would not have new features. SONY uses that part to make Play
Station's OS closed and keep making money of it (it was originally forked
from FreeBSD)
That will ensure what could and what couldn't be done with DoW Mod Manager.

**Comment by Fragjacker** [comment]
> Oops!
I tried to delete the most obvious comments. Probably I went too far :-)
I will pull your version and build upon it. Also I will add the same for my
methods.

If you use Visual Studio 2017 or later, jsut typing three slashes and then pressing enter should auto generate those function doc stubs for you which may come in handy.

> Off topic: do you have more fun with a Python or with a C#? Would you like
DoW Mod Manager to be ported to Python? Just some random thoughts - it's
not like I'm secretly working on that or something :-)

Personally I don't judge any language albeit I have done _far_ more work so far with Python than with any other language. I'd like to get more into C/C++ since that's my most neglected language currently, which is a shame really 😁 .

> Another random thought: we have to add a license for DoW Mod Manager. I'm
sure that noone actually will steal it and start to make money off it but
still :-) Maybe something liberal like MIT, GPLv2 (maybe v3 but some people
don't like it - we have to investigate), or zlib . BSD is too liberal so
anyone could not only sell it but also make it close source so original
authors would not have new features. SONY uses that part to make Play
Station's OS closed and keep making money of it (it was originally forked
from FreeBSD)
That will ensure what could and what couldn't be done with DoW Mod Manager.

Adding a licence is indeed a good idea. I am rooting for the MIT license so far. In fact I should do this right now, better safe then sorry 😬 .

**Comment by IgorTheLight** [comment]
Thanks for the tip! And yes - I'm using VS2019 - it works pretty nice (but
I tried a few other IDEs - JetBrains IDEs are really nice!).
About C/C++ - if you want to make GUI applications I could recommend C++
and Qt Framework (using Qt Creator IDE). I personally didn't work with that
but I watched a few videos and it looks nice :-)
If you just want pure C++ - any IDE/Code Editor would do the job.
MIT license is pretty liberal but still protects you from troubles. So I
have nothing against it. I will add it if you will add it (of course).
About 1.9.0 - I'm working on it!
* Search is ready (in ModDownloaderForm) !
* System Timer Resolution can be changed from 1.0 to 0.5 and back! I have
to contact  tebjan for permission to use part of his tool
https://github.com/tebjan/TimerTool
Well... I'm using it now for testing purposes but I will not make a new
release until he grants his permission (I'm not an asshole).
Also - I'm thinking about adding a link to your GitHub page (like "Visit
Home Page"). Maybe a donate button? Hm? ;-) Just give me the link where to
donate.
I know - almost noone would actually donate but hey - you never know! ;-) I
would donate to tebjan after we will start to use his tool in DoW Mod
Manager
What new features are planned (can't guarantee anything but I will try):
* Ability to set Power Setting to "Maximum" and even unlock and set it to
"Ultimate" (I have to check is that even legal :-) )
* Mod errors handling (most likely just logging and showing to the user)
* Ability to download missing mods (by using my new Search feature)
* What do you think about returning of showing mod versions? I heard that
you deleted it due to misleading in version numbers (sometimes moders just
forget to update the mod version)?
* After that... I'm not sure! Maybe I will ask you to change "Written by
FragJacker " to "Created  by FragJacker & IgorTheLight" as a reward? ;-) If
no - I would still be mentioned in the Changelogs.

**Comment by Fragjacker** [comment]
> * Ability to set Power Setting to "Maximum" and even unlock and set it to
"Ultimate" (I have to check is that even legal :-) )

Insert *Wait, that's illegal* meme here 😀 . I'd say that most laptops have their own power management anyways, so no need to invest time into that.

> * Mod errors handling (most likely just logging and showing to the user)

This on the other hand is a cool idea indeed. Especially to narrow down the critical failure messages when mods crash for not so tech savvy people.

> * Ability to download missing mods (by using my new Search feature)

Would absolutely love to see this happen.

> * What do you think about returning of showing mod versions? I heard that
you deleted it due to misleading in version numbers (sometimes moders just
forget to update the mod version)?

Aye that could be useful to display as well. Question is only how we'll display it. Simply concatenate the version string with the Mod name or make a more sophisticated UI for this with like a table view with colums for Mod names and version number etc.

> * After that... I'm not sure! Maybe I will ask you to change "Written by
FragJacker " to "Created  by FragJacker & IgorTheLight" as a reward? ;-) If
no - I would still be mentioned in the Changelogs.

Yes we can do that. However at that point I'd say that maybe some `About` panel could be used for it where additional info of all the involved creators could be displayed. For a temporary solution we could indeed change the string at the bottom of the window though 😁 .

**Comment by IgorTheLight** [comment]
I'm glad that you liked most of my ideas (mod error logging was your idea
actually :-) )
" Aye that could be useful to display as well. Question is only how we'll
display it. Simply concatenate the version string with the Mod name or make
a more sophisticated UI for this with like a table view with colums for Mod
names and version number etc. " - of course I will choose the simplest way!
And after that I will make it better. Working feature first - cool looking
later! :-)
About adding me - thanks! I will do that just before 1.9.0 will be out.
"About" I will add later. Knowing me - that will be in a few days.

**Comment by IgorTheLight** [comment]
Hi!
You are probably interested in how development is going. It's fine! 1.9.0
will be the biggest release yet! Maybe it's even a good idea to call it
2.0.0?
Here is what I've done:
## Version 1.9.0 (WIP):

- Added ability to search for mods in Mod Downloader
- To achieve this result, the whole ModDownloaderForm was rewritten
- Added System Performance. This tool is able to change system-wise
settings for better performance
- First of the features for System Performance is Timer Resolution (thanks
tebjan for TimerTool). Lowering this value could increase CPU performance
but it also will increase power consumption
- Added tabs to the SystemPerformanceForm
- Added ability to change compatibility settings such as "Run as
Administrator", "Compatibility Mode: Windows XP SP2" and "HDPI Aware" for
the game (only for Soulstorm for now)
- Added ability to see all your System Power Settings
- Added ability to unlock "Ultimate Performance" power plan
- Added ability to disable fullscreen optimizations in Compatibility tab
- Compatibility Settings are supporting all DoW versions now
- Added ability to change Power Plans
- Added ability to open Power Options by opening Control Panel
- Added ability to show DoW Properties

My plans:
- Add versions to the mods (today)
- Add link to your GitHub DoW Mod Manager page (today)
- Add ability to download missing mods (tomorrow and maybe one more day)
- Add ability to show mod errors (another day or 2)
- Add myself to the Authors (in the bottom of the ModManagerForm)
- Add ability to manage Player Profiles (create, select and delete)
- Autoupdater (or maybe "semi-autoupdater" at minimum)

That's too many changes for one version. We will have a
SystemPerformanceForm, a search function, a download missing mod function,
a version showing feature, an error showing feature and a Player Profile
managing feature. I may split it into 1.9.0 and 1.10.0 or make it 2.0.0
(that will have a better promotional effect).
What do you think about the versioning?
You may clone a master branch and see for yourself all new features. Or
just wait until I finish all of that :-)
I want that having a DoW Mod Manager is ALL you need to play vanilla and
modded DoW (all tools in one box).

**Comment by Fragjacker** [comment]
That's some very nice changes indeed! I'd say we can call it 2.0.0 once we also have implemented the auto-downloading/updating as that would be next level indeed.

> Added ability to search for mods in Mod Downloader
To achieve this result, the whole ModDownloaderForm was rewritten
Added System Performance. This tool is able to change system-wise
settings for better performance
 First of the features for System Performance is Timer Resolution (thanks
tebjan for TimerTool). Lowering this value could increase CPU performance
but it also will increase power consumption
Added tabs to the SystemPerformanceForm
Added ability to change compatibility settings such as "Run as
Administrator", "Compatibility Mode: Windows XP SP2" and "HDPI Aware" for
the game (only for Soulstorm for now)
 Added ability to see all your System Power Settings
Added ability to unlock "Ultimate Performance" power plan
Added ability to disable fullscreen optimizations in Compatibility tab
Compatibility Settings are supporting all DoW versions now
Added ability to change Power Plans
Added ability to open Power Options by opening Control Panel
Added ability to show DoW Properties

Like all them changes. We just need to make sure we're not frying them laptop batteries 😀 .

> My plans:
Add versions to the mods (today)
Add link to your GitHub DoW Mod Manager page (today)
Add ability to download missing mods (tomorrow and maybe one more day)
Add ability to show mod errors (another day or 2)
Add myself to the Authors (in the bottom of the ModManagerForm)
Add ability to manage Player Profiles (create, select and delete)
Autoupdater (or maybe "semi-autoupdater" at minimum)

Yes, once this is implemented we can call it 2.0.0. Especially the auto updating utility is what I am looking the most for, since that was my _original_ design intent when creating the Mod Manager. To make handling and fetching mods as easy as possible.

**Comment by IgorTheLight** [comment]
I'm glad to hear that you like it :-)
I already finished those things:
- Added ability to visit DoW Mod Manager's home page on GitHub
- Added IgorTheLight to the authors (thanks, FragJacker!)
- Updated CornCobMan's Fun Mod for Soulstorm  (from 1.87 to 1.88)
- Updated Veteran Mod for Dark Crusade with additional file links that are
required
- Added version descriptions to all mods in ModDownloader
- Added version detection for mods in ModManager
- All Soulstorm mods in modlist (ModDownloaderForm) have a new attribute
now - "ModuleFileName". Dark Crusade and Original later.
- Added ability to find a missing mod
- Added a new mod to download - Dawn Of Skirmish AI Mod (Version 3.20)
- Small code tweaks and optimizations here and there

Only mod errors, Profile management and autoupdater ahead!
Praise the Omnissiah! ;-)

**Comment by IgorTheLight** [comment]
Hi!
My progress to 2.0.0 is going well - only autoupdater implementation
remains. I'm working on it now.
It will be ready just in a few days!
Random questions:
* Did you heard that Ultimate Apocalypse devs have some... difficulties
with each other? Or maybe because of that kind of problems you left them?
;-)
* Did you tried using Linux? You like Terminal so you will like tinkering
with Linux! :-) Probably you are doing something with it already.

**Comment by Fragjacker** [comment]
> Hi!
My progress to 2.0.0 is going well - only autoupdater implementation
remains. I'm working on it now.
It will be ready just in a few days!

Oh wow that's some good news indeed! Are you using the article I linked back a while ago or are you going to do something from scratch or maybe use some pre-made library?

> * Did you heard that Ultimate Apocalypse devs have some... difficulties
with each other? Or maybe because of that kind of problems you left them?
;-)

Yes, there was a split between the majority of the mod devs and the original creator of the mod. Are you saying that there are problems *again?* If yes then I was unaware of this since I am not in touch with UA mod dev anymore.

> * Did you tried using Linux? You like Terminal so you will like tinkering
with Linux! :-) Probably you are doing something with it already.

Of course I did! 😁 I even did some n00b level kernel programming with DKMS in Ubuntu back in the day in my Uni studies. Nowadays I am not doing that much with Linux currently as I am also part time modding other games such as **Stellaris** or just doing some 3D modelling for fun.

**Comment by IgorTheLight** [comment]
Hi!
About autoupdater - I choose to do it myself but if I encounter some big
difficulties - I would switch to your suggested article :-)
I know that's not very time efficient but I'm a chill guy who doesn't
really care about time efficiency ;-)
About UA - I don't know anyone personally - I just heard some rumors that
there is a new drama going on there. Again. And when they woul;d update
their link to a newer DoW Mod Manager? :-)
About "n00b level kernel programming with DKMS" - still more than I did. I
just tried a bunch of different distros and for today I'm having a Linux
Manjaro KDE 20.0.3 on my USB drive. Not like in LiveUSB - a full install on
a drive! And sometimes I just boot in it and do something :-) I tried
building a .NET Core application - it failed. And of course because of
problems with dependencies. I tried to fix it (watched a few videos and
read a few articles) but gave up - too much buzz for a small test project.
You said that you want to play with a C++. I have a few ideas!
* Port any .NET Framework WinForms application to C++ with WinForms. That
would be easy and give you a "taste" of C++
https://stackoverflow.com/questions/42605185/winforms-any-way-to-convert-ui-of-visual-c-project-to-visual-c
(you need to do that in other way around)
* If you would like it - you may try Qt Framework (or alternatives but that
one has Qt Creator - A fully featured IDE with GUI Builder)
About modding - I watched a few Stellaris videos! I really want to try it
someday :-) What other games are you modding? Sins of a Solar Empire? C&C -
Generals? OpenRA? Star Wars -Empires at War?
What of those games would benefit from DoW Mod Manager port? ;-)

**Comment by Fragjacker** [comment]
> About autoupdater - I choose to do it myself but if I encounter some big
difficulties - I would switch to your suggested article :-)
I know that's not very time efficient but I'm a chill guy who doesn't
really care about time efficiency ;-)

That's some good news keep it up!

> About UA - I don't know anyone personally - I just heard some rumors that
there is a new drama going on there. Again. And when they woul;d update
their link to a newer DoW Mod Manager? :-)

Wouldn't surprise me at this point as there was already potential conflict looming at the horizon, before we split, with one of the balancing team. Also they can't update the link to the new Mod Manager since I am not part of the team anymore. Guess in time I will reupload it on the Unification Mod webpage if any. Github release system is _very_ convient for this 😛 .

> About modding - I watched a few Stellaris videos! I really want to try it
someday :-) What other games are you modding? Sins of a Solar Empire? C&C -
Generals? OpenRA? Star Wars -Empires at War?

So far I only have modded Dawn of War Soulstorm, Civilisation: Beyond Earth and lastly Stellaris. The CnC remastered one is pretty interesting since they have uploaded the source code of the project, so one could flatout build custom game .DLL's. It's also written in C++ 😀 .

> What of those games would benefit from DoW Mod Manager port? ;-)

Guess only Dawn of War since the other games have the steam workshop that takes care of business. For Stellaris exists even a dedicated fan-made Mod Manager already! Check it out here: https://github.com/ThibautSF/ParadoxosModManagerRework/

**Comment by IgorTheLight** [comment]
Thanks for the answer!
It's not like you didn't answer ever before :-)
ALL features are ready! Even autoupdater! I wrote it by myself (with a
small StackOverflow search ;-) )
I'm testing everything and if I didn't find anything to fix - i will create
a pull request. Prepare your command line merging tools!
Changelog for 2.0.0 is messy now so I will simplify it.
https://github.com/IgorTheLight/DoW-Mod-Manager/blob/master/changelog.txt
About other games - yes, Steam Workshop is hard to compete with.
About new C&C Remastered - yes mod possibilities are limitless but it also
supports Steam Workshop so... you know... ;-)
But there is another project - OpenRA. It's a free open source C#
implementation of C&C's engine. It supports C&C, Red Alert 1, Dune 2000 and
(almost) Tiberium Sun!
Maybe it needs a mod launcher (I have to investigate).
Would you like to build a current 2.0.0 version and test it? Or you could
cheat a little bit and download it from here:
https://github.com/IgorTheLight/DoW-Mod-Manager/tree/master/DoW%20Mod%20Manager/LatestStable
Just add "v2.0.0" before the  ".exe" and it will be 100% equal to a version
that you could build yourself ;-)

You have quite a big list of games that you modded :-)

I'm not sure what else I want to add to DoW Mod Manager but I have a plan
for 2.0.1 - a few optimizations :-) 2.0.0 is already almost 2 times smaller
than 1.8.2!

Wow! That Mod Launcher is not only for Stellaris! Good job developers!
Java? Well - it works too :-)

**Pull request merged**
