### PR TITLE
Version 1.57 (All resources are now embedded in EXE and  all settings are now stored in INI)

### PR DESCRIPTION
**Pull request by IgorTheLight**
Changelog:
1.57
- Optimized code a little bit. Now application uses 200 Kb less RAM
- Now all image resources are embedded in EXE
1.56
- Fixed a crash when GraphicsConfig.exe couldn't be found
- Fixed a crash when Config file has wrong or corrupted entries
1.551
- Fixed a bug that prevented config file to be readable in some cases
- Renamed a few variables
1.55
- More code refactoring
- Settings are stored in *.ini file now instead of AppData\Local

### CODE REVIEW

**Comment by Fragjacker** [comment]
Oh that's some nice changes there! Especially like how the images are embedded inside the .exe now. That is something I always wanted to do. How did you achieve this? Via the resource manager?

Also there's a merge conflict with the `README.md` file again. Make sure you resolve that proper so we can merge it.

**Comment by IgorTheLight** [comment]
Ah! Problems with README.md. How unoriginal, Mr GitHub! I will fix them :-)
So how I embedded images?
* In Solution Explorer mark every image as "Embedded Resource" instead of
"None"
* Now you have to call them in code in a little bit different way (look and
you will see how I did that).
If you are still confused - that may help:
http://www.csharp411.com/embedded-image-resources/

**Comment by IgorTheLight** [comment]
Are you busy?
I hope you are ok and just have no time to look at this small project :-)

**Comment by Fragjacker** [comment]
Oof yeah I am sorry. I am currently in the finishing phase of my Master Thesis paper and have to divert all my time into it since my due date is the 26.05 and my Profs send me some feedback that I have to take into consideration and rework my paper. 😬 

Once I am done with this I'll come back to this 😀

**Comment by IgorTheLight** [comment]
Oh Ok! Don't bother with that :-)
Good luck with studying!

**Comment by Fragjacker** [comment]
Alright I am back in business now that I finished my Thesis paper 😁 . Gotta review this today!

**Review by Fragjacker — CHANGES_REQUESTED** [review]
# Change Request
## Bug
issue
There is an issue with the Mod Merger now. The activate/deactivate functionality got borked. When selecting an entry on the upper list I should be able to activate/deactivate a mod. This keeps the file still in the list but won't load it in-game. 
## Fix
Make sure to restore their prior functionality again. Disabled mods should appear red and get sorted to the bottom of the loaded Mods list. See the below image for how it should be:
image

**Comment by Fragjacker** [comment]
Other than this your changes look pretty nice and work pretty well! Once you fixed the above issue @IgorTheLight we should be able to merge this.

**Comment by IgorTheLight** [comment]
Oh thanks for reply!
I'll fix it tomorrow. My refactoring probably goes wrong at some lines :-)
I hope your study project went fine!

**Comment by IgorTheLight** [comment]
I fixed the problem!
Please confirm that it's fine now.

**Comment by Fragjacker** [comment]
@IgorTheLight Alright, i'll test it ASAP. BTW I see you wanted to implement Winter Assault support but reverted. What happened? 😀 

Another idea could be to add support for Dawn of War Game of the Year edition as in supporting vanilla DoW too.

**Review by Fragjacker — APPROVED** [review]
The bugs from the previous change request were fixed, all looks OK now!

**Comment by IgorTheLight** [comment]
True - I'm implementing Winter Assault support.
The reason why I reverted the changes is because I want you to accept my
pull request (1.57).
So as you did just that (thank you btw :-) ) I will continue to develop WA
support. Actually - it worked just before I reverted it.
About supporting the original version. Well... I probably add it also! Just
for "100% complete experience".

**Comment by IgorTheLight** [comment]
Hi!
Winter Assault mod support is working! Original Dawn of War mod support is
probably working - I not tested it yet. Mod Manager will ignore original
files if Winter Assault is in the same directory (for now). I will improve
that in the near future :-)
Also I'm preparing new "kinda big" release - 1.60
New features:
+ Winter Assault mod support - already working
+ Original mod support - testing
+ Original and WA LAA patching - working (without any additional work from
me)
+ NEW advanced Start option - High Priority + CPU threads restrictions. It
could improve performance on some systems. If not - it's OFF by default so
no harm is done :-)
More information here:
https://www.moddb.com/members/psykotenshi/blogs/how-to-improve-performance-on-dawn-of-war-soulstorm
The last thing is not working - options don't want to apply. I'm figuring
what's the problem.
I will not make new pull request for now - everything is not tested at all
so 1.57 must be much more stable.
If you are interested I could upload a .NET Core version of DoW Mod
Manager. I'm not very pleased by it for now - GUI Designer is buggy,
application CAN'T be 32-bit and also it takes more RAM (part of the "64-bit
application only" problem). If you are curious - no, I'm not planing to
replace .NET Framework for .NET Core - I see no point in that. It's Open
Source and cross platform but none of that would benefit our little Mod
Manager :-)

**Comment by Fragjacker** [comment]
That's excellent news! Yeah I know psyko tenshi well, he's part of my discord moderators 😁 . Support for Winter Assault and base game is also appreciated.

**Comment by IgorTheLight** [comment]
I'm glad to hear that! :-)
I think I could show my result in a few days. But if you are really bored -
you may build project using my last commit. I mean - if you are really
bored!
Also - do you know someone from Ultimate Apocalypse team? If yes - do they
care about new (hopefully not bugged) features?

**Comment by Fragjacker** [comment]
@IgorTheLight I am a former UA team member. You may know me as Cosmocrat from Moddb. This tool is still demanded in the community and any changes appreciated 😀 .

**Comment by IgorTheLight** [comment]
Wow! That's nice to hear!
About my progress - game threads optimizations are working now! For some
reason not process affinity, nor process priority of the game couldn't be
changed right after it starts. So I have to wait a few seconds after launch
to change it. And of course users wouldn't know about that and probably
would close Mod Manager after starting a game so I had to use
System.Threading to ensure loyalty... I mean... to ensure that process
priority and affinity WILL change no matter what :-)
Original DoW mods are probably supported but I could find them so... :-)
Stable release will be available in a few days.

**Pull request merged**
